// <auto-generated />
using System;
using MedicalServiceSvc.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalServiceSvc.DAL.Migrations
{
    [DbContext(typeof(MedicalServiceDbContext))]
    partial class MedicalServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalServiceSvc.DAL.Models.MedicalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MedicalService");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "GHC101",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comprehensive periodic health check-up",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "General Health Check",
                            Price = 0.1m,
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "CC102",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Heart and vascular health consultation",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cardiology Consultation",
                            Price = 0.1m,
                            SpecialtyId = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "DE103",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Skin care and dermatological check",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dermatology Examination",
                            Price = 0.1m,
                            SpecialtyId = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "INF001",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intravenous infusion therapy service",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Infusion Service",
                            Price = 0.15m,
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 5,
                            Code = "TH001",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Online consultation service for telehealth appointments",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Telehealth Appointment",
                            Price = 0.1m,
                            SpecialtyId = 2
                        },
                        new
                        {
                            Id = 6,
                            Code = "BED-STD-001",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Daily inpatient charge for a standard hospital bed",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Standard Bed Daily Charge",
                            Price = 10m,
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 7,
                            Code = "BED-ELE-002",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Daily inpatient charge for an electric hospital bed",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Electric Bed Daily Charge",
                            Price = 5m,
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 8,
                            Code = "BED-ICU-003",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Daily inpatient charge for an ICU hospital bed",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "ICU Bed Daily Charge",
                            Price = 20m,
                            SpecialtyId = 1
                        });
                });

            modelBuilder.Entity("MedicalServiceSvc.DAL.Models.MedicalServiceRole", b =>
                {
                    b.Property<int>("MedicalServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("MedicalServiceId", "Role");

                    b.ToTable("MedicalServiceRole");

                    b.HasData(
                        new
                        {
                            MedicalServiceId = 1,
                            Role = 3
                        },
                        new
                        {
                            MedicalServiceId = 1,
                            Role = 4
                        },
                        new
                        {
                            MedicalServiceId = 2,
                            Role = 3
                        },
                        new
                        {
                            MedicalServiceId = 3,
                            Role = 3
                        },
                        new
                        {
                            MedicalServiceId = 4,
                            Role = 3
                        },
                        new
                        {
                            MedicalServiceId = 5,
                            Role = 3
                        });
                });

            modelBuilder.Entity("MedicalServiceSvc.DAL.Models.MedicalServiceRole", b =>
                {
                    b.HasOne("MedicalServiceSvc.DAL.Models.MedicalService", "MedicalService")
                        .WithMany("MedicalServiceRoles")
                        .HasForeignKey("MedicalServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalService");
                });

            modelBuilder.Entity("MedicalServiceSvc.DAL.Models.MedicalService", b =>
                {
                    b.Navigation("MedicalServiceRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
