// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaffRequestSvc.DAL.Data;

#nullable disable

namespace StaffRequestSvc.DAL.Migrations
{
    [DbContext(typeof(StaffRequestDbContext))]
    [Migration("20260422074920_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StaffRequestSvc.DAL.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DecidedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LeaveType")
                        .HasColumnType("int");

                    b.Property<int>("LeaveUnit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("LeaveRequest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2026, 3, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 1,
                            FromDate = new DateOnly(2026, 3, 10),
                            IsDeleted = false,
                            LeaveType = 0,
                            LeaveUnit = 0,
                            Reason = "Family vacation",
                            Status = 1,
                            ToDate = new DateOnly(2026, 3, 12)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 4,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FromDate = new DateOnly(2026, 3, 15),
                            IsDeleted = false,
                            LeaveType = 1,
                            LeaveUnit = 0,
                            Reason = "Medical checkup",
                            Status = 0,
                            ToDate = new DateOnly(2026, 3, 15)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 5,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2026, 3, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 1,
                            FromDate = new DateOnly(2026, 3, 20),
                            IsDeleted = false,
                            LeaveType = 3,
                            LeaveUnit = 1,
                            Reason = "Personal errand",
                            ShiftId = 1,
                            Status = 2,
                            ToDate = new DateOnly(2026, 3, 20)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 6,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2026, 3, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 1,
                            FromDate = new DateOnly(2026, 4, 1),
                            IsDeleted = false,
                            LeaveType = 2,
                            LeaveUnit = 0,
                            Reason = "Maternity leave",
                            Status = 1,
                            ToDate = new DateOnly(2026, 6, 30)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 7,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FromDate = new DateOnly(2026, 3, 25),
                            IsDeleted = false,
                            LeaveType = 0,
                            LeaveUnit = 0,
                            Reason = "Travel plan",
                            Status = 0,
                            ToDate = new DateOnly(2026, 3, 28)
                        });
                });

            modelBuilder.Entity("StaffRequestSvc.DAL.Models.SalaryAdvance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DecidedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("PayrollId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SalaryAdvance");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 88m,
                            CreatedBy = 4,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Reason = "Pending advance for family expense",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 128m,
                            CreatedBy = 4,
                            CreationDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 2,
                            IsDeleted = false,
                            Reason = "Approved advance for rent payment",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 72m,
                            CreatedBy = 4,
                            CreationDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 2,
                            IsDeleted = false,
                            Reason = "Rejected advance request",
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 60m,
                            CreatedBy = 4,
                            CreationDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Reason = "Cancelled by doctor before approval",
                            Status = 3
                        },
                        new
                        {
                            Id = 5,
                            Amount = 140m,
                            CreatedBy = 4,
                            CreationDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 2,
                            IsDeleted = false,
                            PayrollId = 2,
                            Reason = "Disbursed advance linked to paid payroll",
                            Status = 4
                        },
                        new
                        {
                            Id = 6,
                            Amount = 260m,
                            CreatedBy = 2,
                            CreationDate = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 6,
                            IsDeleted = false,
                            Reason = "Advance for monthly leadership expenses rejected after review",
                            Status = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 88m,
                            CreatedBy = 5,
                            CreationDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Reason = "Advance for nursing family support pending review",
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            Amount = 180m,
                            CreatedBy = 6,
                            CreationDate = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 2,
                            IsDeleted = false,
                            Reason = "Advance for annual training fee approved by management",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 112m,
                            CreatedBy = 7,
                            CreationDate = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 2,
                            IsDeleted = false,
                            Reason = "Advance for pharmacy licensing cost rejected after review",
                            Status = 2
                        },
                        new
                        {
                            Id = 10,
                            Amount = 128m,
                            CreatedBy = 8,
                            CreationDate = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Reason = "Advance for household payment plan cancelled by staff",
                            Status = 3
                        },
                        new
                        {
                            Id = 11,
                            Amount = 100m,
                            CreatedBy = 9,
                            CreationDate = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 2,
                            IsDeleted = false,
                            PayrollId = 16,
                            Reason = "Advance for campaign travel expense disbursed with payroll",
                            Status = 4
                        },
                        new
                        {
                            Id = 12,
                            Amount = 72m,
                            CreatedBy = 11,
                            CreationDate = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 2,
                            IsDeleted = false,
                            Reason = "Advance for front desk living expense approved by management",
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            Amount = 80m,
                            CreatedBy = 12,
                            CreationDate = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 2,
                            IsDeleted = false,
                            Reason = "Advance for hotline family emergency rejected after review",
                            Status = 2
                        },
                        new
                        {
                            Id = 14,
                            Amount = 92m,
                            CreatedBy = 13,
                            CreationDate = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Reason = "Advance for warehouse transportation cost cancelled by staff",
                            Status = 3
                        },
                        new
                        {
                            Id = 15,
                            Amount = 140m,
                            CreatedBy = 14,
                            CreationDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 2,
                            IsDeleted = false,
                            PayrollId = 24,
                            Reason = "Advance for specialist practice expense #14 disbursed with payroll",
                            Status = 4
                        },
                        new
                        {
                            Id = 16,
                            Amount = 164m,
                            CreatedBy = 15,
                            CreationDate = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Reason = "Advance for specialist practice expense #15 pending review",
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            Amount = 188m,
                            CreatedBy = 16,
                            CreationDate = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 2,
                            IsDeleted = false,
                            Reason = "Advance for specialist practice expense #16 approved by management",
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            Amount = 212m,
                            CreatedBy = 17,
                            CreationDate = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 2,
                            IsDeleted = false,
                            Reason = "Advance for specialist practice expense #17 rejected after review",
                            Status = 2
                        },
                        new
                        {
                            Id = 19,
                            Amount = 236m,
                            CreatedBy = 18,
                            CreationDate = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Reason = "Advance for specialist practice expense #18 cancelled by staff",
                            Status = 3
                        },
                        new
                        {
                            Id = 20,
                            Amount = 140m,
                            CreatedBy = 19,
                            CreationDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 2,
                            IsDeleted = false,
                            PayrollId = 34,
                            Reason = "Advance for specialist practice expense #19 disbursed with payroll",
                            Status = 4
                        },
                        new
                        {
                            Id = 21,
                            Amount = 164m,
                            CreatedBy = 20,
                            CreationDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Reason = "Advance for specialist practice expense #20 pending review",
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            Amount = 188m,
                            CreatedBy = 21,
                            CreationDate = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 2,
                            IsDeleted = false,
                            Reason = "Advance for specialist practice expense #21 approved by management",
                            Status = 1
                        },
                        new
                        {
                            Id = 23,
                            Amount = 212m,
                            CreatedBy = 22,
                            CreationDate = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedAt = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DecidedBy = 2,
                            IsDeleted = false,
                            Reason = "Advance for specialist practice expense #22 rejected after review",
                            Status = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
