// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentSvc.DAL.Data;

#nullable disable

namespace RecruitmentSvc.DAL.Migrations
{
    [DbContext(typeof(RecruitmentDbContext))]
    [Migration("20260406070118_A")]
    partial class A
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentSvc.DAL.Models.Interview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InterviewTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterviewTypeId");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("Interview");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InterviewDate = new DateTime(2025, 2, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            InterviewTypeId = 2,
                            IsDeleted = false,
                            JobApplicationId = 1,
                            Note = "Excellent technical skills and good communication. Recommended for hire.",
                            Result = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InterviewDate = new DateTime(2025, 2, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            InterviewTypeId = 1,
                            IsDeleted = false,
                            JobApplicationId = 2,
                            Note = "Scheduled for technical interview round 2.",
                            Result = 0
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InterviewDate = new DateTime(2025, 2, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            InterviewTypeId = 3,
                            IsDeleted = false,
                            JobApplicationId = 3,
                            Note = "Good experience in nursing. Passed both phone and technical interviews.",
                            Result = 1
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InterviewDate = new DateTime(2029, 2, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            InterviewTypeId = 2,
                            IsDeleted = false,
                            JobApplicationId = 4,
                            Note = "Awaiting final interview result.",
                            Result = 0
                        });
                });

            modelBuilder.Entity("RecruitmentSvc.DAL.Models.InterviewType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("InterviewType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Initial screening via phone call",
                            IsDeleted = false,
                            Name = "Phone Interview"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Technical skills assessment with technical team",
                            IsDeleted = false,
                            Name = "Technical Interview"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Final interview with management",
                            IsDeleted = false,
                            Name = "Final Interview"
                        });
                });

            modelBuilder.Entity("RecruitmentSvc.DAL.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ApplyDate")
                        .HasColumnType("date");

                    b.Property<string>("CVUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("JobPostingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId");

                    b.ToTable("JobApplication");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, District 1, HCMC",
                            ApplicationStatus = 2,
                            ApplyDate = new DateOnly(2025, 1, 15),
                            CVUrl = "JobApplication/ba45fada8c194f78b76b3cc74e907b9d.pdf",
                            DateOfBirth = new DateOnly(1990, 5, 15),
                            Email = "john.smith@email.com",
                            Gender = 0,
                            JobPostingId = 1,
                            Name = "John Smith",
                            Phone = "0912345678"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave, District 3, HCMC",
                            ApplicationStatus = 1,
                            ApplyDate = new DateOnly(2025, 1, 20),
                            CVUrl = "JobApplication/ba45fada8c194f78b76b3cc74e907b9d.pdf",
                            DateOfBirth = new DateOnly(1985, 8, 22),
                            Email = "mquwntran04@gmail.com",
                            Gender = 1,
                            JobPostingId = 1,
                            Name = "Mary Johnson",
                            Phone = "0912345679"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Rd, District 5, HCMC",
                            ApplicationStatus = 2,
                            ApplyDate = new DateOnly(2025, 2, 1),
                            CVUrl = "JobApplication/717a3c36949d4e539b18afb15756e89f.pdf",
                            DateOfBirth = new DateOnly(1992, 3, 10),
                            Email = "david.lee@email.com",
                            Gender = 0,
                            JobPostingId = 2,
                            Name = "David Lee",
                            Phone = "0912345680"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Elm St, District 7, HCMC",
                            ApplicationStatus = 1,
                            ApplyDate = new DateOnly(2025, 2, 5),
                            CVUrl = "JobApplication/ba45fada8c194f78b76b3cc74e907b9d.pdf",
                            DateOfBirth = new DateOnly(1988, 11, 25),
                            Email = "sarah.wilson@email.com",
                            Gender = 1,
                            JobPostingId = 2,
                            Name = "Sarah Wilson",
                            Phone = "0912345681"
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Maple Dr, District 9, HCMC",
                            ApplicationStatus = 0,
                            ApplyDate = new DateOnly(2025, 2, 10),
                            CVUrl = "JobApplication/ba45fada8c194f78b76b3cc74e907b9d.pdf",
                            DateOfBirth = new DateOnly(1995, 7, 8),
                            Email = "mquwntran04@gmail.com",
                            Gender = 0,
                            JobPostingId = 3,
                            Name = "Michael Brown",
                            Phone = "0912345682"
                        });
                });

            modelBuilder.Entity("RecruitmentSvc.DAL.Models.JobPosting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benefit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CloseDate")
                        .HasColumnType("date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<decimal>("SalaryMin")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("JobPosting");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Benefit = "Salary 15-20 million VND, insurance, leave, bonuses, and team activities.",
                            CloseDate = new DateOnly(2029, 12, 31),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage accounting records, invoices, taxes, and financial reports for daily operations.",
                            EmploymentType = 0,
                            IsDeleted = false,
                            Requirement = "Accounting or finance degree, 2-3 years of experience, and accounting software proficiency.",
                            Role = 7,
                            SalaryMin = 50000m,
                            Status = 1,
                            Title = "General Accountant - Xuan Phuong, Hanoi"
                        },
                        new
                        {
                            Id = 2,
                            Benefit = "Salary 15-25 million VND, project bonuses, insurance, leave, and company welfare programs.",
                            CloseDate = new DateOnly(2029, 6, 30),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Coordinate client projects, licensing procedures, and progress reporting with Chinese-speaking stakeholders.",
                            EmploymentType = 0,
                            IsDeleted = false,
                            Requirement = "Bachelor's degree, 3+ years of project management experience, and professional Chinese communication.",
                            Role = 1,
                            SalaryMin = 30000m,
                            Status = 0,
                            Title = "Project Manager (Chinese Communication)"
                        },
                        new
                        {
                            Id = 3,
                            Benefit = "Base salary 8-10 million VND, profit bonus, yearly review, and a dynamic workplace.",
                            CloseDate = new DateOnly(2029, 3, 31),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Research products and customers, optimize product pages, and coordinate creative marketing content.",
                            EmploymentType = 1,
                            IsDeleted = false,
                            Requirement = "Marketing-related degree, basic English, research skills, AI tool familiarity, and creativity.",
                            Role = 8,
                            SalaryMin = 15000m,
                            Status = 1,
                            Title = "Marketing Staff (Product Fresher)"
                        });
                });

            modelBuilder.Entity("RecruitmentSvc.DAL.Models.Interview", b =>
                {
                    b.HasOne("RecruitmentSvc.DAL.Models.InterviewType", "InterviewType")
                        .WithMany("Interviews")
                        .HasForeignKey("InterviewTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecruitmentSvc.DAL.Models.JobApplication", "JobApplication")
                        .WithMany("Interviews")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InterviewType");

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("RecruitmentSvc.DAL.Models.JobApplication", b =>
                {
                    b.HasOne("RecruitmentSvc.DAL.Models.JobPosting", "JobPosting")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("RecruitmentSvc.DAL.Models.InterviewType", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("RecruitmentSvc.DAL.Models.JobApplication", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("RecruitmentSvc.DAL.Models.JobPosting", b =>
                {
                    b.Navigation("JobApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
