// <auto-generated />
using System;
using AuthSvc.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthSvc.DAL.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthSvc.DAL.Models.AuthAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Email\" IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Phone\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"UserId\" IS NOT NULL");

                    b.ToTable("AuthAccount");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0360000002",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0360000003",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0360000004",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nurse@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0360000005",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hr@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0360000006",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pharmacist@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0360000007",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "accountant@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0360000008",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "marketer@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0360000009",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 9
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "receptionist@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0360000011",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hotlineagent@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0360000012",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "inventoryclerk@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0360000013",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor14@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0361000014",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor15@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0361000015",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor16@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0361000016",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor17@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0361000017",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor18@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0361000018",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor19@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0361000019",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor20@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0361000020",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor21@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0361000021",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 21
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor22@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0361000022",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 22
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient39@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000039",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 39
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient40@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000040",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 40
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient41@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000041",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 41
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient42@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000042",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 42
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient43@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000043",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 43
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient44@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000044",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 44
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient45@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000045",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 45
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient46@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000046",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 46
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient47@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000047",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 47
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient48@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000048",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 48
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient49@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000049",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 49
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient50@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000050",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 50
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient51@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000051",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 51
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient52@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000052",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 52
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient53@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000053",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 53
                        },
                        new
                        {
                            Id = 54,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient54@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000054",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 54
                        },
                        new
                        {
                            Id = 55,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient55@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000055",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 55
                        },
                        new
                        {
                            Id = 56,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient56@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000056",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 56
                        },
                        new
                        {
                            Id = 57,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient57@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000057",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 57
                        },
                        new
                        {
                            Id = 58,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient58@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000058",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 58
                        },
                        new
                        {
                            Id = 59,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient59@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000059",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 59
                        },
                        new
                        {
                            Id = 60,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient60@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000060",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 60
                        },
                        new
                        {
                            Id = 61,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient61@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000061",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 61
                        },
                        new
                        {
                            Id = 62,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient62@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000062",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 62
                        },
                        new
                        {
                            Id = 63,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient63@example.com",
                            IsDeleted = false,
                            Password = "$2y$12$ircZ0HzeGiPj9YCFwyqxquJrbp4jk2sQyVXL1RGPkHWYjc0TmDks6",
                            Phone = "0362000063",
                            Provider = 3,
                            ProviderUserId = "",
                            Stage = 2,
                            Status = 1,
                            UserId = 63
                        });
                });

            modelBuilder.Entity("AuthSvc.DAL.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthAccountId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("AuthSvc.DAL.Models.RefreshToken", b =>
                {
                    b.HasOne("AuthSvc.DAL.Models.AuthAccount", "AuthAccount")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AuthAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthAccount");
                });

            modelBuilder.Entity("AuthSvc.DAL.Models.AuthAccount", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
