// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserSvc.DAL.Data;

#nullable disable

namespace UserSvc.DAL.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserSvc.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Address = "111 Dong Khoi, quan 1, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1983, 3, 15),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Manager User",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "222 Ly Thuong Kiet, quan 10, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1992, 8, 15),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Patient User",
                            Role = 2
                        },
                        new
                        {
                            Id = 4,
                            Address = "333 Nguyen Van Cu, quan 5, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1980, 3, 10),
                            Gender = 1,
                            Image = "Staff/2799d78a52ba482aabb2fff1552a11b4.webp",
                            IsDeleted = false,
                            Name = "Doctor User",
                            Role = 3
                        },
                        new
                        {
                            Id = 5,
                            Address = "444 An Duong Vuong, quan 5, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1990, 5, 20),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Nurse User",
                            Role = 4
                        },
                        new
                        {
                            Id = 6,
                            Address = "555 Le Van Sy, quan 3, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1988, 11, 25),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "HR User",
                            Role = 5
                        },
                        new
                        {
                            Id = 7,
                            Address = "666 Cach Mang Thang 8, quan 10, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1987, 7, 12),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Pharmacist User",
                            Role = 6
                        },
                        new
                        {
                            Id = 8,
                            Address = "777 Nguyen Thi Minh Khai, quan 1, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1991, 4, 18),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Accountant User",
                            Role = 7
                        },
                        new
                        {
                            Id = 9,
                            Address = "888 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1993, 9, 5),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Marketer User",
                            Role = 8
                        },
                        new
                        {
                            Id = 11,
                            Address = "100 Hoang Van Thu, quan Tan Binh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1995, 6, 14),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Receptionist User",
                            Role = 10
                        },
                        new
                        {
                            Id = 12,
                            Address = "200 Truong Chinh, quan Tan Phu, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1994, 10, 22),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Hotline Agent User",
                            Role = 11
                        },
                        new
                        {
                            Id = 13,
                            Address = "300 Luy Ban Bich, quan Tan Phu, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1996, 12, 8),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Inventory Clerk User",
                            Role = 12
                        },
                        new
                        {
                            Id = 14,
                            Address = "150 Nguyen Du, quan 1, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1978, 1, 1),
                            Gender = 1,
                            Image = "Staff/e775bca93b33420da05be0ff2260bf55.webp",
                            IsDeleted = false,
                            Name = "Nguyen Quoc Bao",
                            Role = 3
                        },
                        new
                        {
                            Id = 15,
                            Address = "151 Nguyen Du, quan 2, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1979, 2, 2),
                            Gender = 2,
                            Image = "Staff/93f6e4c206bf4dd68bba2451c45f6f10.webp",
                            IsDeleted = false,
                            Name = "Tran Minh Quan",
                            Role = 3
                        },
                        new
                        {
                            Id = 16,
                            Address = "152 Nguyen Du, quan 3, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1980, 3, 3),
                            Gender = 1,
                            Image = "Staff/511d363b7db842c19a5f302a208b65e2.webp",
                            IsDeleted = false,
                            Name = "Le Hoang Phuc",
                            Role = 3
                        },
                        new
                        {
                            Id = 17,
                            Address = "153 Nguyen Du, quan 4, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1981, 4, 4),
                            Gender = 2,
                            Image = "Staff/4aac037d513a4a3cb8e46f51bbd5a9f5.webp",
                            IsDeleted = false,
                            Name = "Pham Duc Thinh",
                            Role = 3
                        },
                        new
                        {
                            Id = 18,
                            Address = "154 Nguyen Du, quan 5, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1982, 5, 5),
                            Gender = 1,
                            Image = "Staff/700ecf6913ab4417959e6bfababf22e0.webp",
                            IsDeleted = false,
                            Name = "Vo Gia Huy",
                            Role = 3
                        },
                        new
                        {
                            Id = 19,
                            Address = "155 Nguyen Du, quan 6, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1983, 6, 6),
                            Gender = 2,
                            Image = "Staff/a7b1670d959f43059676e25b2a07eabf.webp",
                            IsDeleted = false,
                            Name = "Dang Tuan Kiet",
                            Role = 3
                        },
                        new
                        {
                            Id = 20,
                            Address = "156 Nguyen Du, quan 1, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1984, 7, 7),
                            Gender = 1,
                            Image = "Staff/9ef3ae9834be48ab93407983fcb17711.webp",
                            IsDeleted = false,
                            Name = "Bui Thanh Nam",
                            Role = 3
                        },
                        new
                        {
                            Id = 21,
                            Address = "157 Nguyen Du, quan 2, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1985, 8, 8),
                            Gender = 2,
                            Image = "Staff/3af8d6407b7446638ab1d3f015f49290.webp",
                            IsDeleted = false,
                            Name = "Doan Quang Hiep",
                            Role = 3
                        },
                        new
                        {
                            Id = 22,
                            Address = "158 Nguyen Du, quan 3, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1986, 9, 9),
                            Gender = 1,
                            Image = "Staff/9168d20b24264cd88731852aa898501f.webp",
                            IsDeleted = false,
                            Name = "Hoang Anh Khoa",
                            Role = 3
                        },
                        new
                        {
                            Id = 39,
                            Address = "210 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1989, 4, 1),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Nguyen Hoang Minh",
                            Role = 2
                        },
                        new
                        {
                            Id = 40,
                            Address = "211 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1990, 5, 3),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Tran Gia Han",
                            Role = 2
                        },
                        new
                        {
                            Id = 41,
                            Address = "212 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1991, 6, 5),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Le Duc Anh",
                            Role = 2
                        },
                        new
                        {
                            Id = 42,
                            Address = "213 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1992, 7, 7),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Pham Thu Trang",
                            Role = 2
                        },
                        new
                        {
                            Id = 43,
                            Address = "214 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1993, 8, 9),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Vo Quynh Nhu",
                            Role = 2
                        },
                        new
                        {
                            Id = 44,
                            Address = "215 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1994, 9, 11),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Dang Thanh Tung",
                            Role = 2
                        },
                        new
                        {
                            Id = 45,
                            Address = "216 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1995, 10, 13),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Bui Ngoc Mai",
                            Role = 2
                        },
                        new
                        {
                            Id = 46,
                            Address = "217 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1996, 11, 15),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Do Gia Bao",
                            Role = 2
                        },
                        new
                        {
                            Id = 47,
                            Address = "218 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1997, 12, 17),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Hoang Tu Linh",
                            Role = 2
                        },
                        new
                        {
                            Id = 48,
                            Address = "219 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1998, 1, 19),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Phan Minh Khang",
                            Role = 2
                        },
                        new
                        {
                            Id = 49,
                            Address = "220 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1999, 2, 21),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Huynh Bao Chau",
                            Role = 2
                        },
                        new
                        {
                            Id = 50,
                            Address = "221 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2000, 3, 23),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Ngo Thanh Truc",
                            Role = 2
                        },
                        new
                        {
                            Id = 51,
                            Address = "222 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1989, 4, 25),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Truong Gia Huy",
                            Role = 2
                        },
                        new
                        {
                            Id = 52,
                            Address = "223 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1990, 5, 27),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Duong Nhat Vy",
                            Role = 2
                        },
                        new
                        {
                            Id = 53,
                            Address = "224 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1991, 6, 2),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Ly Minh Thu",
                            Role = 2
                        },
                        new
                        {
                            Id = 54,
                            Address = "225 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1992, 7, 4),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Mai Quoc Khanh",
                            Role = 2
                        },
                        new
                        {
                            Id = 55,
                            Address = "226 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1993, 8, 6),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Cao Bao Ngoc",
                            Role = 2
                        },
                        new
                        {
                            Id = 56,
                            Address = "227 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1994, 9, 8),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Dinh Thanh Ha",
                            Role = 2
                        },
                        new
                        {
                            Id = 57,
                            Address = "228 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1995, 10, 10),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Chu Ngoc Han",
                            Role = 2
                        },
                        new
                        {
                            Id = 58,
                            Address = "229 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1996, 11, 12),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Lam Minh Quan",
                            Role = 2
                        },
                        new
                        {
                            Id = 59,
                            Address = "230 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1997, 12, 14),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Ta Bao Tran",
                            Role = 2
                        },
                        new
                        {
                            Id = 60,
                            Address = "231 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1998, 1, 16),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Ton That Nhu Y",
                            Role = 2
                        },
                        new
                        {
                            Id = 61,
                            Address = "232 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1999, 2, 18),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Kieu Thanh Nhan",
                            Role = 2
                        },
                        new
                        {
                            Id = 62,
                            Address = "233 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2000, 3, 20),
                            Gender = 2,
                            IsDeleted = false,
                            Name = "Quach Bao Han",
                            Role = 2
                        },
                        new
                        {
                            Id = 63,
                            Address = "234 Dien Bien Phu, quan Binh Thanh, thanh pho HCM",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1989, 4, 22),
                            Gender = 1,
                            IsDeleted = false,
                            Name = "Thai Anh Thu",
                            Role = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
