// <auto-generated />
using System;
using AppointmentSvc.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppointmentSvc.DAL.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    partial class AppointmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppointmentSvc.DAL.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentMeetingType")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentPaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MedicalHistoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.Property<string>("TimeSlotSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("Appointment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentMeetingType = 1,
                            AppointmentPaymentStatus = 1,
                            AppointmentStatus = 1,
                            CompletedDate = new DateTime(2025, 1, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateOnly(2025, 1, 1),
                            IsDeleted = false,
                            MedicalHistoryId = 2,
                            PatientId = 3,
                            Purpose = "Follow-up Consultation",
                            SpecialtyId = 3,
                            TimeSlotId = 8,
                            TimeSlotSnapshot = "{\"id\":8,\"time\":\"10:30:00\"}"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentMeetingType = 1,
                            AppointmentPaymentStatus = 2,
                            AppointmentStatus = 2,
                            CancelledDate = new DateTime(2025, 1, 2, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateOnly(2025, 1, 2),
                            IsDeleted = false,
                            PatientId = 3,
                            Purpose = "Neurology Checkup",
                            SpecialtyId = 2,
                            TimeSlotId = 10,
                            TimeSlotSnapshot = "{\"id\":10,\"time\":\"13:30:00\"}"
                        });
                });

            modelBuilder.Entity("AppointmentSvc.DAL.Models.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacityPerDoctor")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("Time")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Time\" IS NOT NULL");

                    b.ToTable("TimeSlot");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityPerDoctor = 4,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CapacityPerDoctor = 4,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(7, 30, 0)
                        },
                        new
                        {
                            Id = 3,
                            CapacityPerDoctor = 3,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CapacityPerDoctor = 3,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(8, 30, 0)
                        },
                        new
                        {
                            Id = 5,
                            CapacityPerDoctor = 2,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            CapacityPerDoctor = 2,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(9, 30, 0)
                        },
                        new
                        {
                            Id = 7,
                            CapacityPerDoctor = 1,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            CapacityPerDoctor = 1,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(10, 30, 0)
                        },
                        new
                        {
                            Id = 9,
                            CapacityPerDoctor = 4,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            CapacityPerDoctor = 4,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(13, 30, 0)
                        },
                        new
                        {
                            Id = 11,
                            CapacityPerDoctor = 3,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(14, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            CapacityPerDoctor = 3,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(14, 30, 0)
                        },
                        new
                        {
                            Id = 13,
                            CapacityPerDoctor = 2,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            CapacityPerDoctor = 2,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(15, 30, 0)
                        },
                        new
                        {
                            Id = 15,
                            CapacityPerDoctor = 1,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            CapacityPerDoctor = 1,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Time = new TimeOnly(16, 30, 0)
                        });
                });

            modelBuilder.Entity("AppointmentSvc.DAL.Models.Appointment", b =>
                {
                    b.HasOne("AppointmentSvc.DAL.Models.TimeSlot", "TimeSlot")
                        .WithMany("Appointments")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("AppointmentSvc.DAL.Models.TimeSlot", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
