// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaffSvc.DAL.Data;

#nullable disable

namespace StaffSvc.DAL.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    partial class StaffDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StaffSvc.DAL.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Name\" IS NOT NULL");

                    b.ToTable("Qualification");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Basic licensed doctor",
                            IsDeleted = false,
                            Name = "General Practitioner"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Specialist certification level I",
                            IsDeleted = false,
                            Name = "Specialist Level I"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Specialist certification level II",
                            IsDeleted = false,
                            Name = "Specialist Level II"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Master degree in medicine",
                            IsDeleted = false,
                            Name = "Master of Medicine"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "PhD in medical science",
                            IsDeleted = false,
                            Name = "Doctor of Philosophy"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Doctor in residency training",
                            IsDeleted = false,
                            Name = "Resident Doctor"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Senior consulting doctor",
                            IsDeleted = false,
                            Name = "Consultant Physician"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Certified surgical doctor",
                            IsDeleted = false,
                            Name = "Surgeon"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Teaching medical staff",
                            IsDeleted = false,
                            Name = "Medical Lecturer"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Medical research specialist",
                            IsDeleted = false,
                            Name = "Clinical Researcher"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Specialist in public health",
                            IsDeleted = false,
                            Name = "Public Health Specialist"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Healthcare management professional",
                            IsDeleted = false,
                            Name = "Hospital Administrator"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Medical laboratory technology specialist",
                            IsDeleted = false,
                            Name = "Medical Technologist"
                        });
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.RegionalWage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyWage")
                        .HasColumnType("numeric(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Code\" IS NOT NULL");

                    b.ToTable("RegionalWage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            MonthlyWage = 5000000m
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            MonthlyWage = 4500000m
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            MonthlyWage = 4000000m
                        });
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMedical")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Name\" IS NOT NULL");

                    b.ToTable("Specialty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cardiology focuses on diagnosing, treating, and preventing diseases of the heart and vascular system.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "General Internal Medicine provides comprehensive long-term care for adults.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "General Internal Medicine"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "OB/GYN focuses on women's reproductive health and pregnancy.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Obstetrics and Gynecology"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Orthopedics treats musculoskeletal system disorders.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pediatrics focuses on child and adolescent health.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dermatology treats skin, hair, and nail diseases.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Neurology treats nervous system disorders.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ophthalmology treats eye and vision disorders.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Ophthalmology"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ENT treats ear, nose, and throat conditions.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Otolaryngology (ENT)"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Urology treats urinary tract and male reproductive system.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Urology"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nephrology focuses on kidney diseases.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Nephrology"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pulmonology treats lung and respiratory diseases.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Pulmonology"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gastroenterology treats digestive system disorders.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Gastroenterology"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Endocrinology treats hormone disorders.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Endocrinology"
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rheumatology treats autoimmune and joint diseases.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Rheumatology"
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hematology treats blood-related diseases.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Hematology"
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oncology treats cancer.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Oncology"
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Radiology uses imaging for diagnosis.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Radiology"
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Psychiatry treats mental health disorders.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Psychiatry"
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rehabilitation restores physical function.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Rehabilitation Medicine"
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Anesthesiology manages anesthesia and pain.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Anesthesiology"
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Emergency Medicine handles acute conditions.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Emergency Medicine"
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Infectious Diseases treats infections.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Infectious Diseases"
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Family Medicine provides holistic care.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Family Medicine"
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Geriatrics focuses on elderly care.",
                            IsDeleted = false,
                            IsMedical = true,
                            Name = "Geriatrics"
                        });
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BankCode")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DependentQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("QualificationId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QualificationId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AccountNumber = "9704360000000002",
                            BankCode = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 0,
                            IsDeleted = false,
                            QualificationId = 2,
                            SpecialtyId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            AccountNumber = "9704070000000004",
                            BankCode = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 1,
                            IsDeleted = false,
                            QualificationId = 4,
                            SpecialtyId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            AccountNumber = "9704180000000005",
                            BankCode = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 0,
                            IsDeleted = false,
                            QualificationId = 5,
                            SpecialtyId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            AccountNumber = "9704150000000006",
                            BankCode = 4,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 2,
                            IsDeleted = false,
                            QualificationId = 6,
                            SpecialtyId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            AccountNumber = "9704160000000007",
                            BankCode = 5,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 1,
                            IsDeleted = false,
                            QualificationId = 7,
                            SpecialtyId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            AccountNumber = "9704230000000008",
                            BankCode = 6,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 0,
                            IsDeleted = false,
                            QualificationId = 8,
                            SpecialtyId = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            AccountNumber = "9704320000000009",
                            BankCode = 7,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 0,
                            IsDeleted = false,
                            QualificationId = 9,
                            SpecialtyId = 9,
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            AccountNumber = "9704050000000011",
                            BankCode = 8,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 1,
                            IsDeleted = false,
                            QualificationId = 11,
                            SpecialtyId = 11,
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            AccountNumber = "9704260000000012",
                            BankCode = 9,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 0,
                            IsDeleted = false,
                            QualificationId = 12,
                            SpecialtyId = 12,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            AccountNumber = "9704480000000013",
                            BankCode = 10,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 2,
                            IsDeleted = false,
                            QualificationId = 13,
                            SpecialtyId = 13,
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            AccountNumber = "9704010000000014",
                            BankCode = 0,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 0,
                            IsDeleted = false,
                            QualificationId = 1,
                            SpecialtyId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            AccountNumber = "9704020000000015",
                            BankCode = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 1,
                            IsDeleted = false,
                            QualificationId = 2,
                            SpecialtyId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            AccountNumber = "9704030000000016",
                            BankCode = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 2,
                            IsDeleted = false,
                            QualificationId = 3,
                            SpecialtyId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            AccountNumber = "9704040000000017",
                            BankCode = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 0,
                            IsDeleted = false,
                            QualificationId = 4,
                            SpecialtyId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            AccountNumber = "9704050000000018",
                            BankCode = 4,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 1,
                            IsDeleted = false,
                            QualificationId = 5,
                            SpecialtyId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            AccountNumber = "9704060000000019",
                            BankCode = 5,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 2,
                            IsDeleted = false,
                            QualificationId = 6,
                            SpecialtyId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            AccountNumber = "9704070000000020",
                            BankCode = 6,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 0,
                            IsDeleted = false,
                            QualificationId = 7,
                            SpecialtyId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            AccountNumber = "9704080000000021",
                            BankCode = 7,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 1,
                            IsDeleted = false,
                            QualificationId = 8,
                            SpecialtyId = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            AccountNumber = "9704090000000022",
                            BankCode = 8,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DependentQuantity = 2,
                            IsDeleted = false,
                            QualificationId = 9,
                            SpecialtyId = 9,
                            Status = 0
                        });
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.StaffCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("ExpiredDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("IssuedDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StaffCertificateTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificateNo")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"CertificateNo\" IS NOT NULL");

                    b.HasIndex("StaffCertificateTypeId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffCertificate");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CertificateNo = "ACLS-002",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiredDate = new DateOnly(2025, 6, 10),
                            IsDeleted = false,
                            IssuedBy = "American Heart Association",
                            IssuedDate = new DateOnly(2023, 6, 10),
                            StaffCertificateTypeId = 2,
                            StaffId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CertificateNo = "PALS-003",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiredDate = new DateOnly(2024, 9, 5),
                            IsDeleted = false,
                            IssuedBy = "American Heart Association",
                            IssuedDate = new DateOnly(2022, 9, 5),
                            StaffCertificateTypeId = 3,
                            StaffId = 5,
                            Status = 1
                        });
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.StaffCertificateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScopeOfPractice")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"Name\" IS NOT NULL");

                    b.ToTable("StaffCertificateType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BLS Provider",
                            ScopeOfPractice = "Basic Life Support for clinical staff"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ACLS Provider",
                            ScopeOfPractice = "Advanced cardiovascular life support"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PALS Provider",
                            ScopeOfPractice = "Pediatric advanced life support"
                        });
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.StaffContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ContractType")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<decimal>("InsuranceSalaryRate")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("RegionalWageId")
                        .HasColumnType("int");

                    b.Property<string>("SignatureImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("SignedDate")
                        .HasColumnType("date");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WorkingHoursPerWeek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractCode")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"ContractCode\" IS NOT NULL");

                    b.HasIndex("RegionalWageId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffContract");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            ContractCode = "HD002",
                            ContractType = 0,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2030, 12, 31),
                            HourlyRate = 2.2m,
                            InsuranceSalaryRate = 1m,
                            IsDeleted = false,
                            RegionalWageId = 2,
                            SignedDate = new DateOnly(2024, 6, 1),
                            StaffId = 2,
                            StartDate = new DateOnly(2024, 6, 1),
                            Status = 0,
                            WorkingHoursPerWeek = 40
                        },
                        new
                        {
                            Id = 4,
                            ContractCode = "HD004",
                            ContractType = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2030, 12, 31),
                            HourlyRate = 3m,
                            InsuranceSalaryRate = 1m,
                            IsDeleted = false,
                            RegionalWageId = 1,
                            SignedDate = new DateOnly(2024, 3, 1),
                            StaffId = 4,
                            StartDate = new DateOnly(2024, 3, 1),
                            Status = 0,
                            WorkingHoursPerWeek = 40
                        },
                        new
                        {
                            Id = 5,
                            ContractCode = "HD005",
                            ContractType = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2030, 12, 31),
                            HourlyRate = 1.4m,
                            InsuranceSalaryRate = 1m,
                            IsDeleted = false,
                            RegionalWageId = 3,
                            SignedDate = new DateOnly(2024, 9, 1),
                            StaffId = 5,
                            StartDate = new DateOnly(2024, 9, 1),
                            Status = 0,
                            WorkingHoursPerWeek = 40
                        },
                        new
                        {
                            Id = 6,
                            ContractCode = "HD006",
                            ContractType = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HourlyRate = 4m,
                            InsuranceSalaryRate = 1m,
                            IsDeleted = false,
                            RegionalWageId = 1,
                            SignedDate = new DateOnly(2023, 5, 1),
                            StaffId = 6,
                            StartDate = new DateOnly(2023, 5, 1),
                            Status = 0,
                            WorkingHoursPerWeek = 40
                        },
                        new
                        {
                            Id = 7,
                            ContractCode = "HD007",
                            ContractType = 0,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2030, 12, 31),
                            HourlyRate = 2m,
                            InsuranceSalaryRate = 1m,
                            IsDeleted = false,
                            RegionalWageId = 2,
                            SignedDate = new DateOnly(2024, 10, 1),
                            StaffId = 7,
                            StartDate = new DateOnly(2024, 10, 1),
                            Status = 0,
                            WorkingHoursPerWeek = 40
                        },
                        new
                        {
                            Id = 8,
                            ContractCode = "HD008",
                            ContractType = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2030, 12, 31),
                            HourlyRate = 3.2m,
                            InsuranceSalaryRate = 1m,
                            IsDeleted = false,
                            RegionalWageId = 1,
                            SignedDate = new DateOnly(2024, 2, 1),
                            StaffId = 8,
                            StartDate = new DateOnly(2024, 2, 1),
                            Status = 0,
                            WorkingHoursPerWeek = 40
                        },
                        new
                        {
                            Id = 9,
                            ContractCode = "HD009",
                            ContractType = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HourlyRate = 3.8m,
                            InsuranceSalaryRate = 1m,
                            IsDeleted = false,
                            RegionalWageId = 2,
                            SignedDate = new DateOnly(2023, 8, 15),
                            StaffId = 9,
                            StartDate = new DateOnly(2023, 8, 15),
                            Status = 0,
                            WorkingHoursPerWeek = 40
                        },
                        new
                        {
                            Id = 11,
                            ContractCode = "HD011",
                            ContractType = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2030, 12, 31),
                            HourlyRate = 2.8m,
                            InsuranceSalaryRate = 1m,
                            IsDeleted = false,
                            RegionalWageId = 1,
                            SignedDate = new DateOnly(2024, 4, 1),
                            StaffId = 11,
                            StartDate = new DateOnly(2024, 4, 1),
                            Status = 0,
                            WorkingHoursPerWeek = 40
                        },
                        new
                        {
                            Id = 12,
                            ContractCode = "HD012",
                            ContractType = 0,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2030, 12, 31),
                            HourlyRate = 2.08m,
                            InsuranceSalaryRate = 1m,
                            IsDeleted = false,
                            RegionalWageId = 2,
                            SignedDate = new DateOnly(2024, 11, 1),
                            StaffId = 12,
                            StartDate = new DateOnly(2024, 11, 1),
                            Status = 0,
                            WorkingHoursPerWeek = 40
                        },
                        new
                        {
                            Id = 13,
                            ContractCode = "HD013",
                            ContractType = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HourlyRate = 3.6m,
                            InsuranceSalaryRate = 1m,
                            IsDeleted = false,
                            RegionalWageId = 1,
                            SignedDate = new DateOnly(2023, 12, 1),
                            StaffId = 13,
                            StartDate = new DateOnly(2023, 12, 1),
                            Status = 0,
                            WorkingHoursPerWeek = 40
                        });
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.StaffGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Name\" IS NOT NULL");

                    b.ToTable("StaffGroup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Doctors"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Nurses"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "TeleHealth Staff"
                        });
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.StaffGroupMember", b =>
                {
                    b.Property<int>("StaffGroupId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("StaffGroupId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffGroupMember");

                    b.HasData(
                        new
                        {
                            StaffGroupId = 1,
                            StaffId = 4
                        },
                        new
                        {
                            StaffGroupId = 2,
                            StaffId = 5
                        },
                        new
                        {
                            StaffGroupId = 3,
                            StaffId = 4
                        },
                        new
                        {
                            StaffGroupId = 3,
                            StaffId = 12
                        });
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.Staff", b =>
                {
                    b.HasOne("StaffSvc.DAL.Models.Qualification", "Qualification")
                        .WithMany("Staffs")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StaffSvc.DAL.Models.Specialty", "Specialty")
                        .WithMany("Staffs")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Qualification");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.StaffCertificate", b =>
                {
                    b.HasOne("StaffSvc.DAL.Models.StaffCertificateType", "StaffCertificateType")
                        .WithMany("StaffCertificates")
                        .HasForeignKey("StaffCertificateTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StaffSvc.DAL.Models.Staff", "Staff")
                        .WithMany("StaffCertificates")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("StaffCertificateType");
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.StaffContract", b =>
                {
                    b.HasOne("StaffSvc.DAL.Models.RegionalWage", "RegionalWage")
                        .WithMany()
                        .HasForeignKey("RegionalWageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StaffSvc.DAL.Models.Staff", "Staff")
                        .WithMany("StaffContracts")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegionalWage");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.StaffGroupMember", b =>
                {
                    b.HasOne("StaffSvc.DAL.Models.StaffGroup", "StaffGroup")
                        .WithMany("StaffGroupMembers")
                        .HasForeignKey("StaffGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaffSvc.DAL.Models.Staff", "Staff")
                        .WithMany("StaffGroupMembers")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("StaffGroup");
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.Qualification", b =>
                {
                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.Specialty", b =>
                {
                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.Staff", b =>
                {
                    b.Navigation("StaffCertificates");

                    b.Navigation("StaffContracts");

                    b.Navigation("StaffGroupMembers");
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.StaffCertificateType", b =>
                {
                    b.Navigation("StaffCertificates");
                });

            modelBuilder.Entity("StaffSvc.DAL.Models.StaffGroup", b =>
                {
                    b.Navigation("StaffGroupMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
