// <auto-generated />
using System;
using BillingSvc.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillingSvc.DAL.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260330181952_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BillingSvc.DAL.Models.Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChargeSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChargeType")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MedicalServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Charge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChargeSnapshot = "{\"medicalServiceName\":\"General Health Check\",\"medicalServiceDescription\":\"Comprehensive periodic health check-up\"}",
                            ChargeType = 0,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceId = 1,
                            IsDeleted = false,
                            MedicalServiceId = 1,
                            Quantity = 1,
                            UnitPrice = 500m
                        },
                        new
                        {
                            Id = 2,
                            ChargeSnapshot = "{\"medicalServiceName\":\"Cardiology Consultation\",\"medicalServiceDescription\":\"Heart and vascular health consultation\"}",
                            ChargeType = 1,
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceId = 1,
                            IsDeleted = false,
                            MedicalServiceId = 2,
                            Quantity = 1,
                            UnitPrice = 700m
                        },
                        new
                        {
                            Id = 3,
                            ChargeSnapshot = "{\"medicalServiceName\":\"Dermatology Consultation\",\"medicalServiceDescription\":\"Skin health and treatment consultation\"}",
                            ChargeType = 0,
                            CreationDate = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceId = 2,
                            IsDeleted = false,
                            MedicalServiceId = 3,
                            Quantity = 1,
                            UnitPrice = 600m
                        },
                        new
                        {
                            Id = 4,
                            ChargeSnapshot = "{\"medicalServiceName\":\"General Health Check\",\"medicalServiceDescription\":\"Comprehensive periodic health check-up\"}",
                            ChargeType = 0,
                            CreationDate = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceId = 3,
                            IsDeleted = false,
                            MedicalServiceId = 1,
                            Quantity = 2,
                            UnitPrice = 500m
                        });
                });

            modelBuilder.Entity("BillingSvc.DAL.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClinicalMedicalOrderId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("InvoiceStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MedicalHistoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"InvoiceNumber\" IS NOT NULL");

                    b.ToTable("Invoice");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicalMedicalOrderId = "64f000000000000000000001",
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-OPD-20260101-000000",
                            InvoiceStatus = 1,
                            IsDeleted = false,
                            MedicalHistoryId = 1,
                            PaymentDate = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-OPD-20260102-000000",
                            InvoiceStatus = 1,
                            IsDeleted = false,
                            MedicalHistoryId = 1,
                            PaymentDate = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ClinicalMedicalOrderId = "64f000000000000000000003",
                            CreationDate = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-IPD-20260103-000000",
                            InvoiceStatus = 1,
                            IsDeleted = false,
                            MedicalHistoryId = 2,
                            PaymentDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BillingSvc.DAL.Models.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int>("ChargeId")
                        .HasColumnType("int");

                    b.Property<string>("ClinicalMedicalOrderDetailId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RefundStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"ChargeId\" IS NOT NULL");

                    b.ToTable("Refund");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChargeId = 2,
                            ClinicalMedicalOrderDetailId = "64f000000000000000000001",
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Reason = "Failed to do service due to technical issue",
                            RefundStatus = 0
                        });
                });

            modelBuilder.Entity("BillingSvc.DAL.Models.Charge", b =>
                {
                    b.HasOne("BillingSvc.DAL.Models.Invoice", "Invoice")
                        .WithMany("Charges")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("BillingSvc.DAL.Models.Refund", b =>
                {
                    b.HasOne("BillingSvc.DAL.Models.Charge", "Charge")
                        .WithOne("Refund")
                        .HasForeignKey("BillingSvc.DAL.Models.Refund", "ChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Charge");
                });

            modelBuilder.Entity("BillingSvc.DAL.Models.Charge", b =>
                {
                    b.Navigation("Refund");
                });

            modelBuilder.Entity("BillingSvc.DAL.Models.Invoice", b =>
                {
                    b.Navigation("Charges");
                });
#pragma warning restore 612, 618
        }
    }
}
