// <auto-generated />
using System;
using InventorySvc.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventorySvc.DAL.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventorySvc.DAL.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastImportDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SKUCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastImportDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxQuantity = 1000,
                            MinQuantity = 50,
                            Quantity = 500,
                            SKUCode = "PA1BO2050"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastImportDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxQuantity = 800,
                            MinQuantity = 30,
                            Quantity = 300,
                            SKUCode = "PA1BO3050"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastImportDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxQuantity = 500,
                            MinQuantity = 20,
                            Quantity = 120,
                            SKUCode = "AM2BO2050"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastImportDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxQuantity = 500,
                            MinQuantity = 30,
                            Quantity = 200,
                            SKUCode = "AM2BL1050"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastImportDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxQuantity = 400,
                            MinQuantity = 20,
                            Quantity = 150,
                            SKUCode = "VC3BO2010"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastImportDate = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxQuantity = 900,
                            MinQuantity = 40,
                            Quantity = 480,
                            SKUCode = "PA1BL1250"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastImportDate = new DateTime(2025, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxQuantity = 500,
                            MinQuantity = 25,
                            Quantity = 220,
                            SKUCode = "VC3BO2050"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastImportDate = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxQuantity = 350,
                            MinQuantity = 20,
                            Quantity = 140,
                            SKUCode = "AM3BO3010"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastImportDate = new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxQuantity = 300,
                            MinQuantity = 15,
                            Quantity = 100,
                            SKUCode = "AM3BO3260"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastImportDate = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxQuantity = 250,
                            MinQuantity = 15,
                            Quantity = 95,
                            SKUCode = "BI5BO1050"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastImportDate = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxQuantity = 280,
                            MinQuantity = 20,
                            Quantity = 130,
                            SKUCode = "DI6BO2050"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastImportDate = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxQuantity = 420,
                            MinQuantity = 30,
                            Quantity = 180,
                            SKUCode = "NA4BO2550"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastImportDate = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxQuantity = 220,
                            MinQuantity = 10,
                            Quantity = 75,
                            SKUCode = "NA7BO5010"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LastImportDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxQuantity = 520,
                            MinQuantity = 35,
                            Quantity = 260,
                            SKUCode = "OR8BO2032"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
