// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderSvc.DAL.Data;

#nullable disable

namespace OrderSvc.DAL.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderSvc.DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPickupAtStore")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginPrice")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalDiscountAmount")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VoucherCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalPrice = 5.5m,
                            IsDeleted = false,
                            IsPickupAtStore = false,
                            OrderDate = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = 0,
                            OriginPrice = 5.5m,
                            PatientId = 3,
                            TotalDiscountAmount = 0m
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalPrice = 2.55m,
                            IsDeleted = false,
                            IsPickupAtStore = true,
                            OrderDate = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = 1,
                            OriginPrice = 3m,
                            PaidDate = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            TotalDiscountAmount = 0.45m
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryDate = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalPrice = 7.1m,
                            IsDeleted = false,
                            IsPickupAtStore = false,
                            OrderDate = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = 3,
                            OriginPrice = 8m,
                            PaidDate = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            TotalDiscountAmount = 0.9m,
                            VoucherCode = "PV-WELCOME10"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalPrice = 1.2m,
                            IsDeleted = false,
                            IsPickupAtStore = true,
                            OrderDate = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = 4,
                            OriginPrice = 1.2m,
                            PatientId = 3,
                            TotalDiscountAmount = 0m
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalPrice = 4.05m,
                            IsDeleted = false,
                            IsPickupAtStore = false,
                            OrderDate = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = 2,
                            OriginPrice = 4.5m,
                            PaidDate = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            TotalDiscountAmount = 0.45m
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalPrice = 0m,
                            IsDeleted = false,
                            IsPickupAtStore = true,
                            OrderDate = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = 1,
                            OriginPrice = 3m,
                            PaidDate = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            TotalDiscountAmount = 3m,
                            VoucherCode = "PV-FIRST5"
                        });
                });

            modelBuilder.Entity("OrderSvc.DAL.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("SKUCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<string>("MedicineSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18, 2)");

                    b.HasKey("OrderId", "SKUCode");

                    b.ToTable("OrderDetail");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            SKUCode = "PA1BO2050",
                            DiscountAmount = 0m,
                            MedicineSnapshot = "{\"medicineName\":\"Paracetamol 500\",\"medicineBrand\":\"Stada\",\"medicineImages\":[\"Medicine/thuoc-paracetamol-650-mg-mediplantex-3-c1880_1770294316_bdee440d.webp\"],\"medicineUnit\":\"Tablet\"}",
                            Quantity = 2,
                            UnitPrice = 1.5m
                        },
                        new
                        {
                            OrderId = 1,
                            SKUCode = "AM2BO2050",
                            DiscountAmount = 0m,
                            MedicineSnapshot = "{\"medicineName\":\"Amoxicillin 500\",\"medicineBrand\":\"Medipharma\",\"medicineImages\":[\"Medicine/amoxicillin_1770294305_24f46c57.webp\"],\"medicineUnit\":\"Capsule\"}",
                            Quantity = 1,
                            UnitPrice = 2.5m
                        },
                        new
                        {
                            OrderId = 2,
                            SKUCode = "VC3BO2050",
                            DiscountAmount = 0.45m,
                            MedicineSnapshot = "{\"medicineName\":\"Vitamin C 1000\",\"medicineBrand\":\"Nature\\u0027s Way\",\"medicineImages\":[\"Medicine/VitaminC_1770294282_a543fa89.webp\"],\"medicineUnit\":\"Effervescent\"}",
                            Quantity = 1,
                            UnitPrice = 3m
                        },
                        new
                        {
                            OrderId = 3,
                            SKUCode = "PA1BO3050",
                            DiscountAmount = 0m,
                            MedicineSnapshot = "{\"medicineName\":\"Paracetamol 500\",\"medicineBrand\":\"Stada\",\"medicineImages\":[\"Medicine/thuoc-paracetamol-650-mg-mediplantex-3-c1880_1770294316_bdee440d.webp\"],\"medicineUnit\":\"Tablet\"}",
                            Quantity = 1,
                            UnitPrice = 2m
                        },
                        new
                        {
                            OrderId = 3,
                            SKUCode = "VC3BO2050",
                            DiscountAmount = 0.45m,
                            MedicineSnapshot = "{\"medicineName\":\"Vitamin C 1000\",\"medicineBrand\":\"Nature\\u0027s Way\",\"medicineImages\":[\"Medicine/VitaminC_1770294282_a543fa89.webp\"],\"medicineUnit\":\"Effervescent\"}",
                            Quantity = 2,
                            UnitPrice = 3m
                        },
                        new
                        {
                            OrderId = 4,
                            SKUCode = "AM2BO1050",
                            DiscountAmount = 0m,
                            MedicineSnapshot = "{\"medicineName\":\"Amoxicillin 500\",\"medicineBrand\":\"Medipharma\",\"medicineImages\":[\"Medicine/amoxicillin_1770294305_24f46c57.webp\"],\"medicineUnit\":\"Capsule\"}",
                            Quantity = 1,
                            UnitPrice = 1.2m
                        },
                        new
                        {
                            OrderId = 5,
                            SKUCode = "PA1BO2050",
                            DiscountAmount = 0m,
                            MedicineSnapshot = "{\"medicineName\":\"Paracetamol 500\",\"medicineBrand\":\"Stada\",\"medicineImages\":[\"Medicine/thuoc-paracetamol-650-mg-mediplantex-3-c1880_1770294316_bdee440d.webp\"],\"medicineUnit\":\"Tablet\"}",
                            Quantity = 1,
                            UnitPrice = 1.5m
                        },
                        new
                        {
                            OrderId = 5,
                            SKUCode = "VC3BO2050",
                            DiscountAmount = 0.45m,
                            MedicineSnapshot = "{\"medicineName\":\"Vitamin C 1000\",\"medicineBrand\":\"Nature\\u0027s Way\",\"medicineImages\":[\"Medicine/VitaminC_1770294282_a543fa89.webp\"],\"medicineUnit\":\"Effervescent\"}",
                            Quantity = 1,
                            UnitPrice = 3m
                        },
                        new
                        {
                            OrderId = 6,
                            SKUCode = "VC3BO2050",
                            DiscountAmount = 3m,
                            MedicineSnapshot = "{\"medicineName\":\"Vitamin C 1000\",\"medicineBrand\":\"Nature\\u0027s Way\",\"medicineImages\":[\"Medicine/VitaminC_1770294282_a543fa89.webp\"],\"medicineUnit\":\"Effervescent\"}",
                            Quantity = 1,
                            UnitPrice = 3m
                        });
                });

            modelBuilder.Entity("OrderSvc.DAL.Models.OrderDetail", b =>
                {
                    b.HasOne("OrderSvc.DAL.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderSvc.DAL.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
