// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeleHealthSvc.DAL.Data;

#nullable disable

namespace TeleHealthSvc.DAL.Migrations
{
    [DbContext(typeof(TeleHealthDbContext))]
    [Migration("20260406071918_A")]
    partial class A
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeleHealthSvc.DAL.Models.TeleRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoomDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomCode")
                        .IsUnique()
                        .HasFilter("\"RoomCode\" IS NOT NULL");

                    b.HasIndex("RoomDisplayName")
                        .IsUnique()
                        .HasFilter("\"RoomDisplayName\" IS NOT NULL");

                    b.HasIndex("SpecialtyId")
                        .IsUnique()
                        .HasFilter("\"SpecialtyId\" IS NOT NULL");

                    b.ToTable("TeleRoom");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomCode = "TELEROOM_CARDIOLOGY",
                            RoomDisplayName = "Cardiology TeleRoom",
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoomCode = "TELEROOM_GENERAL_INTERNAL_MEDICINE",
                            RoomDisplayName = "General Internal Medicine TeleRoom",
                            SpecialtyId = 2
                        },
                        new
                        {
                            Id = 3,
                            RoomCode = "TELEROOM_OBSTETRICS_GYNECOLOGY",
                            RoomDisplayName = "Obstetrics and Gynecology TeleRoom",
                            SpecialtyId = 3
                        },
                        new
                        {
                            Id = 4,
                            RoomCode = "TELEROOM_ORTHOPEDICS",
                            RoomDisplayName = "Orthopedics TeleRoom",
                            SpecialtyId = 4
                        },
                        new
                        {
                            Id = 5,
                            RoomCode = "TELEROOM_PEDIATRICS",
                            RoomDisplayName = "Pediatrics TeleRoom",
                            SpecialtyId = 5
                        },
                        new
                        {
                            Id = 6,
                            RoomCode = "TELEROOM_DERMATOLOGY",
                            RoomDisplayName = "Dermatology TeleRoom",
                            SpecialtyId = 6
                        },
                        new
                        {
                            Id = 7,
                            RoomCode = "TELEROOM_NEUROLOGY",
                            RoomDisplayName = "Neurology TeleRoom",
                            SpecialtyId = 7
                        },
                        new
                        {
                            Id = 8,
                            RoomCode = "TELEROOM_OPHTHALMOLOGY",
                            RoomDisplayName = "Ophthalmology TeleRoom",
                            SpecialtyId = 8
                        },
                        new
                        {
                            Id = 9,
                            RoomCode = "TELEROOM_ENT",
                            RoomDisplayName = "Otolaryngology (ENT) TeleRoom",
                            SpecialtyId = 9
                        },
                        new
                        {
                            Id = 10,
                            RoomCode = "TELEROOM_UROLOGY",
                            RoomDisplayName = "Urology TeleRoom",
                            SpecialtyId = 10
                        },
                        new
                        {
                            Id = 11,
                            RoomCode = "TELEROOM_NEPHROLOGY",
                            RoomDisplayName = "Nephrology TeleRoom",
                            SpecialtyId = 11
                        },
                        new
                        {
                            Id = 12,
                            RoomCode = "TELEROOM_PULMONOLOGY",
                            RoomDisplayName = "Pulmonology TeleRoom",
                            SpecialtyId = 12
                        },
                        new
                        {
                            Id = 13,
                            RoomCode = "TELEROOM_GASTROENTEROLOGY",
                            RoomDisplayName = "Gastroenterology TeleRoom",
                            SpecialtyId = 13
                        },
                        new
                        {
                            Id = 14,
                            RoomCode = "TELEROOM_ENDOCRINOLOGY",
                            RoomDisplayName = "Endocrinology TeleRoom",
                            SpecialtyId = 14
                        },
                        new
                        {
                            Id = 15,
                            RoomCode = "TELEROOM_RHEUMATOLOGY",
                            RoomDisplayName = "Rheumatology TeleRoom",
                            SpecialtyId = 15
                        },
                        new
                        {
                            Id = 16,
                            RoomCode = "TELEROOM_HEMATOLOGY",
                            RoomDisplayName = "Hematology TeleRoom",
                            SpecialtyId = 16
                        },
                        new
                        {
                            Id = 17,
                            RoomCode = "TELEROOM_ONCOLOGY",
                            RoomDisplayName = "Oncology TeleRoom",
                            SpecialtyId = 17
                        },
                        new
                        {
                            Id = 18,
                            RoomCode = "TELEROOM_RADIOLOGY",
                            RoomDisplayName = "Radiology TeleRoom",
                            SpecialtyId = 18
                        },
                        new
                        {
                            Id = 19,
                            RoomCode = "TELEROOM_PSYCHIATRY",
                            RoomDisplayName = "Psychiatry TeleRoom",
                            SpecialtyId = 19
                        },
                        new
                        {
                            Id = 20,
                            RoomCode = "TELEROOM_REHABILITATION_MEDICINE",
                            RoomDisplayName = "Rehabilitation Medicine TeleRoom",
                            SpecialtyId = 20
                        },
                        new
                        {
                            Id = 21,
                            RoomCode = "TELEROOM_ANESTHESIOLOGY",
                            RoomDisplayName = "Anesthesiology TeleRoom",
                            SpecialtyId = 21
                        },
                        new
                        {
                            Id = 22,
                            RoomCode = "TELEROOM_EMERGENCY_MEDICINE",
                            RoomDisplayName = "Emergency Medicine TeleRoom",
                            SpecialtyId = 22
                        },
                        new
                        {
                            Id = 23,
                            RoomCode = "TELEROOM_INFECTIOUS_DISEASES",
                            RoomDisplayName = "Infectious Diseases TeleRoom",
                            SpecialtyId = 23
                        },
                        new
                        {
                            Id = 24,
                            RoomCode = "TELEROOM_FAMILY_MEDICINE",
                            RoomDisplayName = "Family Medicine TeleRoom",
                            SpecialtyId = 24
                        },
                        new
                        {
                            Id = 25,
                            RoomCode = "TELEROOM_GERIATRICS",
                            RoomDisplayName = "Geriatrics TeleRoom",
                            SpecialtyId = 25
                        });
                });

            modelBuilder.Entity("TeleHealthSvc.DAL.Models.TeleSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CredentialMetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TeleRoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeleRoomId");

                    b.ToTable("TeleSession");
                });

            modelBuilder.Entity("TeleHealthSvc.DAL.Models.TeleSession", b =>
                {
                    b.HasOne("TeleHealthSvc.DAL.Models.TeleRoom", null)
                        .WithMany("TeleSessions")
                        .HasForeignKey("TeleRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TeleHealthSvc.DAL.Models.TeleRoom", b =>
                {
                    b.Navigation("TeleSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
