// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupplierSvc.DAL.Data;

#nullable disable

namespace SupplierSvc.DAL.Migrations
{
    [DbContext(typeof(SupplierDbContext))]
    [Migration("20260422145820_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupplierSvc.DAL.Models.Import", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImportRequestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImportRequestId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"ImportRequestId\" IS NOT NULL");

                    b.ToTable("Import");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportRequestId = 1,
                            IsDeleted = false,
                            ManagerId = 1,
                            Note = "Seed Import 1",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportRequestId = 2,
                            IsDeleted = false,
                            ManagerId = 2,
                            Note = "Seed Import 2",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportRequestId = 3,
                            IsDeleted = false,
                            ManagerId = 3,
                            Note = "Seed Import 3",
                            SupplierId = 3
                        });
                });

            modelBuilder.Entity("SupplierSvc.DAL.Models.ImportDetail", b =>
                {
                    b.Property<int>("ImportId")
                        .HasColumnType("int");

                    b.Property<string>("SKUCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18, 2)");

                    b.HasKey("ImportId", "SKUCode");

                    b.ToTable("ImportDetail");

                    b.HasData(
                        new
                        {
                            ImportId = 1,
                            SKUCode = "PA1BO2050",
                            Quantity = 100,
                            UnitPrice = 100m
                        },
                        new
                        {
                            ImportId = 2,
                            SKUCode = "AM2BO2050",
                            Quantity = 200,
                            UnitPrice = 100m
                        },
                        new
                        {
                            ImportId = 3,
                            SKUCode = "VC3BO2010",
                            Quantity = 300,
                            UnitPrice = 100m
                        });
                });

            modelBuilder.Entity("SupplierSvc.DAL.Models.ImportRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RequestDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ImportRequest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RequestDate = new DateOnly(2026, 3, 3),
                            Status = 4
                        },
                        new
                        {
                            Id = 2,
                            ApprovedByUserId = 2,
                            CreationDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RequestDate = new DateOnly(2026, 3, 3),
                            Status = 4
                        },
                        new
                        {
                            Id = 3,
                            ApprovedByUserId = 3,
                            CreationDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RequestDate = new DateOnly(2026, 3, 3),
                            Status = 4
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RequestDate = new DateOnly(2026, 3, 8),
                            Status = 0
                        });
                });

            modelBuilder.Entity("SupplierSvc.DAL.Models.ImportRequestDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImportRequestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MedicineSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("RequestQuantity")
                        .HasColumnType("int");

                    b.Property<string>("SKUCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRequestId");

                    b.ToTable("ImportRequestDetail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 13,
                            CreationDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportRequestId = 1,
                            IsDeleted = false,
                            MedicineSnapshot = "{\"medicineName\":\"Paracetamol\",\"unitPrice\":100}",
                            RequestQuantity = 100,
                            SKUCode = "PA1BO2050"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 13,
                            CreationDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportRequestId = 2,
                            IsDeleted = false,
                            MedicineSnapshot = "{\"medicineName\":\"Amoxicillin\",\"unitPrice\":100}",
                            RequestQuantity = 200,
                            SKUCode = "AM2BO2050"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 13,
                            CreationDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportRequestId = 3,
                            IsDeleted = false,
                            MedicineSnapshot = "{\"medicineName\":\"Vitamin C\",\"unitPrice\":100}",
                            RequestQuantity = 300,
                            SKUCode = "VC3BO2010"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 13,
                            CreationDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImportRequestId = 4,
                            IsDeleted = false,
                            MedicineSnapshot = "{\"medicineName\":\"Paracetamol\"}",
                            RequestQuantity = 150,
                            SKUCode = "PA1BO3050"
                        });
                });

            modelBuilder.Entity("SupplierSvc.DAL.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Email\" IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Name\" IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Phone\" IS NOT NULL");

                    b.ToTable("Supplier");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Health St, Wellness City",
                            CreationDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "contact@medisupply.example",
                            IsDeleted = false,
                            Name = "MediSupply Co",
                            Note = "Primary supplier for general medicines",
                            Phone = "0987284222"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Pharmacy Ave, Caretown",
                            CreationDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sales@pharmadirect.example",
                            IsDeleted = false,
                            Name = "PharmaDirect Ltd",
                            Note = "Fast delivery partner",
                            Phone = "0987282222"
                        },
                        new
                        {
                            Id = 3,
                            Address = "9 Clinic Rd, Healborough",
                            CreationDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "support@healthplus.example",
                            IsDeleted = false,
                            Name = "HealthPlus Distributors",
                            Note = "Specializes in OTC products",
                            Phone = "09872382211"
                        });
                });

            modelBuilder.Entity("SupplierSvc.DAL.Models.Import", b =>
                {
                    b.HasOne("SupplierSvc.DAL.Models.ImportRequest", "ImportRequest")
                        .WithOne("Import")
                        .HasForeignKey("SupplierSvc.DAL.Models.Import", "ImportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportRequest");
                });

            modelBuilder.Entity("SupplierSvc.DAL.Models.ImportDetail", b =>
                {
                    b.HasOne("SupplierSvc.DAL.Models.Import", "Import")
                        .WithMany("ImportDetails")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Import");
                });

            modelBuilder.Entity("SupplierSvc.DAL.Models.ImportRequestDetail", b =>
                {
                    b.HasOne("SupplierSvc.DAL.Models.ImportRequest", "ImportRequest")
                        .WithMany("ImportRequestDetails")
                        .HasForeignKey("ImportRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportRequest");
                });

            modelBuilder.Entity("SupplierSvc.DAL.Models.Import", b =>
                {
                    b.Navigation("ImportDetails");
                });

            modelBuilder.Entity("SupplierSvc.DAL.Models.ImportRequest", b =>
                {
                    b.Navigation("Import");

                    b.Navigation("ImportRequestDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
