// <auto-generated />
using System;
using AttendanceSvc.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceSvc.DAL.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    [Migration("20260330181539_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttendanceSvc.DAL.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Attendance");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogTime = new DateTime(2025, 1, 1, 16, 0, 0, 0, DateTimeKind.Utc),
                            LogType = 0,
                            StaffId = 4
                        },
                        new
                        {
                            Id = 2,
                            LogTime = new DateTime(2025, 1, 1, 20, 0, 0, 0, DateTimeKind.Utc),
                            LogType = 1,
                            StaffId = 4
                        },
                        new
                        {
                            Id = 3,
                            LogTime = new DateTime(2025, 1, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                            LogType = 1,
                            StaffId = 4
                        },
                        new
                        {
                            Id = 4,
                            LogTime = new DateTime(2025, 1, 1, 16, 0, 0, 0, DateTimeKind.Utc),
                            LogType = 0,
                            StaffId = 5
                        },
                        new
                        {
                            Id = 5,
                            LogTime = new DateTime(2025, 1, 1, 20, 0, 0, 0, DateTimeKind.Utc),
                            LogType = 1,
                            StaffId = 5
                        },
                        new
                        {
                            Id = 6,
                            LogTime = new DateTime(2025, 1, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                            LogType = 1,
                            StaffId = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
