// <auto-generated />
using System;
using InpatientResourceSvc.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InpatientResourceSvc.DAL.Migrations
{
    [DbContext(typeof(InpatientResourceDbContext))]
    [Migration("20260406192303_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.Bed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BedCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BedCategoryId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Code\" IS NOT NULL");

                    b.HasIndex("RoomId");

                    b.ToTable("Bed");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BedCategoryId = 1,
                            Code = "A101-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            BedCategoryId = 1,
                            Code = "A101-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            BedCategoryId = 2,
                            Code = "A102-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            BedCategoryId = 2,
                            Code = "A102-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            BedCategoryId = 3,
                            Code = "B201-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            BedCategoryId = 3,
                            Code = "B201-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            BedCategoryId = 1,
                            Code = "A103-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            BedCategoryId = 1,
                            Code = "A103-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            BedCategoryId = 1,
                            Code = "A104-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            BedCategoryId = 1,
                            Code = "A104-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            BedCategoryId = 1,
                            Code = "A105-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            BedCategoryId = 1,
                            Code = "A105-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            BedCategoryId = 1,
                            Code = "A106-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            BedCategoryId = 1,
                            Code = "A106-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            BedCategoryId = 2,
                            Code = "A107-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            BedCategoryId = 2,
                            Code = "A107-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            BedCategoryId = 1,
                            Code = "A108-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 9,
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            BedCategoryId = 1,
                            Code = "A108-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 9,
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            BedCategoryId = 1,
                            Code = "B202-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 10,
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            BedCategoryId = 1,
                            Code = "B202-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 10,
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            BedCategoryId = 1,
                            Code = "B203-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 11,
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            BedCategoryId = 1,
                            Code = "B203-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 11,
                            Status = 0
                        },
                        new
                        {
                            Id = 23,
                            BedCategoryId = 1,
                            Code = "B204-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 12,
                            Status = 0
                        },
                        new
                        {
                            Id = 24,
                            BedCategoryId = 1,
                            Code = "B204-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 12,
                            Status = 0
                        },
                        new
                        {
                            Id = 25,
                            BedCategoryId = 1,
                            Code = "B205-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 13,
                            Status = 0
                        },
                        new
                        {
                            Id = 26,
                            BedCategoryId = 1,
                            Code = "B205-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 13,
                            Status = 1
                        },
                        new
                        {
                            Id = 27,
                            BedCategoryId = 1,
                            Code = "B206-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 14,
                            Status = 0
                        },
                        new
                        {
                            Id = 28,
                            BedCategoryId = 1,
                            Code = "B206-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 14,
                            Status = 0
                        },
                        new
                        {
                            Id = 29,
                            BedCategoryId = 1,
                            Code = "B207-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 15,
                            Status = 0
                        },
                        new
                        {
                            Id = 30,
                            BedCategoryId = 1,
                            Code = "B207-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 15,
                            Status = 0
                        },
                        new
                        {
                            Id = 31,
                            BedCategoryId = 1,
                            Code = "B208-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 16,
                            Status = 0
                        },
                        new
                        {
                            Id = 32,
                            BedCategoryId = 1,
                            Code = "B208-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 16,
                            Status = 0
                        },
                        new
                        {
                            Id = 33,
                            BedCategoryId = 2,
                            Code = "B209-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 17,
                            Status = 0
                        },
                        new
                        {
                            Id = 34,
                            BedCategoryId = 2,
                            Code = "B209-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 17,
                            Status = 0
                        },
                        new
                        {
                            Id = 35,
                            BedCategoryId = 1,
                            Code = "B210-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 18,
                            Status = 0
                        },
                        new
                        {
                            Id = 36,
                            BedCategoryId = 1,
                            Code = "B210-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 18,
                            Status = 0
                        },
                        new
                        {
                            Id = 37,
                            BedCategoryId = 1,
                            Code = "C101-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 19,
                            Status = 0
                        },
                        new
                        {
                            Id = 38,
                            BedCategoryId = 1,
                            Code = "C101-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 19,
                            Status = 0
                        },
                        new
                        {
                            Id = 39,
                            BedCategoryId = 1,
                            Code = "C102-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 20,
                            Status = 0
                        },
                        new
                        {
                            Id = 40,
                            BedCategoryId = 1,
                            Code = "C102-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 20,
                            Status = 0
                        },
                        new
                        {
                            Id = 41,
                            BedCategoryId = 3,
                            Code = "C103-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 21,
                            Status = 0
                        },
                        new
                        {
                            Id = 42,
                            BedCategoryId = 3,
                            Code = "C103-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 21,
                            Status = 0
                        },
                        new
                        {
                            Id = 43,
                            BedCategoryId = 3,
                            Code = "C104-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 22,
                            Status = 0
                        },
                        new
                        {
                            Id = 44,
                            BedCategoryId = 3,
                            Code = "C104-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 22,
                            Status = 0
                        },
                        new
                        {
                            Id = 45,
                            BedCategoryId = 1,
                            Code = "C105-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 23,
                            Status = 0
                        },
                        new
                        {
                            Id = 46,
                            BedCategoryId = 1,
                            Code = "C105-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 23,
                            Status = 0
                        },
                        new
                        {
                            Id = 47,
                            BedCategoryId = 1,
                            Code = "C106-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 24,
                            Status = 0
                        },
                        new
                        {
                            Id = 48,
                            BedCategoryId = 1,
                            Code = "C106-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 24,
                            Status = 0
                        },
                        new
                        {
                            Id = 49,
                            BedCategoryId = 1,
                            Code = "C107-01",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 25,
                            Status = 0
                        },
                        new
                        {
                            Id = 50,
                            BedCategoryId = 1,
                            Code = "C107-02",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RoomId = 25,
                            Status = 0
                        });
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.BedCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Code\" IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Name\" IS NOT NULL");

                    b.ToTable("BedCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BED-STD-001",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Basic manual hospital bed",
                            IsDeleted = false,
                            Name = "Standard Bed"
                        },
                        new
                        {
                            Id = 2,
                            Code = "BED-ELE-002",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Motorized adjustable hospital bed with remote control",
                            IsDeleted = false,
                            Name = "Electric Bed"
                        },
                        new
                        {
                            Id = 3,
                            Code = "BED-ICU-003",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Advanced ICU bed with monitoring capabilities",
                            IsDeleted = false,
                            Name = "ICU Bed"
                        });
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.BedOccupancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BedId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FromDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MedicalHistoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("OccupancyStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ToDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransferNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BedId");

                    b.ToTable("BedOccupancy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BedId = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FromDateTime = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MedicalHistoryId = 3,
                            OccupancyStatus = 0
                        },
                        new
                        {
                            Id = 2,
                            BedId = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FromDateTime = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MedicalHistoryId = 4,
                            OccupancyStatus = 0
                        });
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Name\" IS NOT NULL");

                    b.ToTable("Building");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Location = "Main Campus, North Wing",
                            Name = "Alpha Building"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Location = "Main Campus, South Wing",
                            Name = "Beta Building"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Location = "Emergency Wing, East Side",
                            Name = "Gamma Building"
                        });
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId", "FloorNumber")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"BuildingId\" IS NOT NULL AND \"FloorNumber\" IS NOT NULL");

                    b.ToTable("Floor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorNumber = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorNumber = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            BuildingId = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorNumber = 1,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("RoomCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Code\" IS NOT NULL");

                    b.HasIndex("FloorId");

                    b.HasIndex("RoomCategoryId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "A101",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 1,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Code = "A102",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 1,
                            IsDeleted = false,
                            RoomCategoryId = 2,
                            SpecialtyId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Code = "B201",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 2,
                            IsDeleted = false,
                            RoomCategoryId = 3,
                            SpecialtyId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            Code = "A103",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 1,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Code = "A104",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 1,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Code = "A105",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 1,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            Code = "A106",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 1,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            Code = "A107",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 1,
                            IsDeleted = false,
                            RoomCategoryId = 2,
                            SpecialtyId = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            Code = "A108",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 1,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 9,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            Code = "B202",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 2,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 10,
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            Code = "B203",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 2,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 11,
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            Code = "B204",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 2,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 12,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            Code = "B205",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 2,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 13,
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            Code = "B206",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 2,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 14,
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            Code = "B207",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 2,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 15,
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            Code = "B208",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 2,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 16,
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            Code = "B209",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 2,
                            IsDeleted = false,
                            RoomCategoryId = 2,
                            SpecialtyId = 17,
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            Code = "B210",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 2,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 18,
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            Code = "C101",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 3,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 19,
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            Code = "C102",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 3,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 20,
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            Code = "C103",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 3,
                            IsDeleted = false,
                            RoomCategoryId = 3,
                            SpecialtyId = 21,
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            Code = "C104",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 3,
                            IsDeleted = false,
                            RoomCategoryId = 3,
                            SpecialtyId = 22,
                            Status = 0
                        },
                        new
                        {
                            Id = 23,
                            Code = "C105",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 3,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 23,
                            Status = 0
                        },
                        new
                        {
                            Id = 24,
                            Code = "C106",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 3,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 24,
                            Status = 0
                        },
                        new
                        {
                            Id = 25,
                            Code = "C107",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FloorId = 3,
                            IsDeleted = false,
                            RoomCategoryId = 1,
                            SpecialtyId = 25,
                            Status = 0
                        });
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.RoomCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Name\" IS NOT NULL");

                    b.ToTable("RoomCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Basic hospital room with standard facilities",
                            IsDeleted = false,
                            Name = "Standard Room"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium room with advanced amenities and privacy",
                            IsDeleted = false,
                            Name = "VIP Room"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Intensive Care Unit for critical patients",
                            IsDeleted = false,
                            Name = "ICU"
                        });
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.RoomCategoryRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Role")
                        .IsUnique()
                        .HasFilter("\"Role\" IS NOT NULL");

                    b.ToTable("RoomCategoryRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            Role = 3
                        },
                        new
                        {
                            Id = 3,
                            Role = 4
                        });
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.RoomCategoryRoleMapping", b =>
                {
                    b.Property<int>("RoomCategoryRoleId")
                        .HasColumnType("int");

                    b.Property<int>("RoomCategoryId")
                        .HasColumnType("int");

                    b.HasKey("RoomCategoryRoleId", "RoomCategoryId");

                    b.HasIndex("RoomCategoryId");

                    b.ToTable("RoomCategoryRoleMapping");

                    b.HasData(
                        new
                        {
                            RoomCategoryRoleId = 1,
                            RoomCategoryId = 1
                        },
                        new
                        {
                            RoomCategoryRoleId = 3,
                            RoomCategoryId = 1
                        },
                        new
                        {
                            RoomCategoryRoleId = 1,
                            RoomCategoryId = 2
                        },
                        new
                        {
                            RoomCategoryRoleId = 2,
                            RoomCategoryId = 2
                        },
                        new
                        {
                            RoomCategoryRoleId = 3,
                            RoomCategoryId = 2
                        },
                        new
                        {
                            RoomCategoryRoleId = 1,
                            RoomCategoryId = 3
                        },
                        new
                        {
                            RoomCategoryRoleId = 2,
                            RoomCategoryId = 3
                        },
                        new
                        {
                            RoomCategoryRoleId = 3,
                            RoomCategoryId = 3
                        });
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.Bed", b =>
                {
                    b.HasOne("InpatientResourceSvc.DAL.Models.BedCategory", "BedCategory")
                        .WithMany("Beds")
                        .HasForeignKey("BedCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InpatientResourceSvc.DAL.Models.Room", "Room")
                        .WithMany("Beds")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BedCategory");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.BedOccupancy", b =>
                {
                    b.HasOne("InpatientResourceSvc.DAL.Models.Bed", "Bed")
                        .WithMany("BedOccupancies")
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bed");
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.Floor", b =>
                {
                    b.HasOne("InpatientResourceSvc.DAL.Models.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.Room", b =>
                {
                    b.HasOne("InpatientResourceSvc.DAL.Models.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InpatientResourceSvc.DAL.Models.RoomCategory", "RoomCategory")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Floor");

                    b.Navigation("RoomCategory");
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.RoomCategoryRoleMapping", b =>
                {
                    b.HasOne("InpatientResourceSvc.DAL.Models.RoomCategory", "RoomCategory")
                        .WithMany("RoomCategoryRoleMappings")
                        .HasForeignKey("RoomCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InpatientResourceSvc.DAL.Models.RoomCategoryRole", "RoomCategoryRole")
                        .WithMany("RoomCategoryRoleMappings")
                        .HasForeignKey("RoomCategoryRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomCategory");

                    b.Navigation("RoomCategoryRole");
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.Bed", b =>
                {
                    b.Navigation("BedOccupancies");
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.BedCategory", b =>
                {
                    b.Navigation("Beds");
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.Room", b =>
                {
                    b.Navigation("Beds");
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.RoomCategory", b =>
                {
                    b.Navigation("RoomCategoryRoleMappings");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("InpatientResourceSvc.DAL.Models.RoomCategoryRole", b =>
                {
                    b.Navigation("RoomCategoryRoleMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
