// <auto-generated />
using System;
using MedicineSvc.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicineSvc.DAL.Migrations
{
    [DbContext(typeof(MedicineDbContext))]
    partial class MedicineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicineSvc.DAL.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Images")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("MedicineCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("MedicineUnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicineCategoryId");

                    b.HasIndex("MedicineUnitId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"Name\" IS NOT NULL");

                    b.ToTable("Medicine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Stada",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Images = "[\"Medicine/thuoc-paracetamol-650-mg-mediplantex-3-c1880_1770294316_bdee440d.webp\"]",
                            IsDeleted = false,
                            IsPublic = true,
                            MedicineCategoryId = 2,
                            MedicineUnitId = 1,
                            Name = "Paracetamol 500",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Medipharma",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Images = "[\"Medicine/amoxicillin_1770294305_24f46c57.webp\"]",
                            IsDeleted = false,
                            IsPublic = false,
                            MedicineCategoryId = 1,
                            MedicineUnitId = 2,
                            Name = "Amoxicillin 500",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Nature's Way",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Images = "[\"Medicine/VitaminC_1770294282_a543fa89.webp\"]",
                            IsDeleted = false,
                            IsPublic = true,
                            MedicineCategoryId = 3,
                            MedicineUnitId = 9,
                            Name = "Vitamin C 1000",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Medipharma",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Images = "[\"Medicine/001f8ae49f5449feaed195262defce06.webp\"]",
                            IsDeleted = false,
                            IsPublic = false,
                            MedicineCategoryId = 1,
                            MedicineUnitId = 3,
                            Name = "Amoxicillin Syrup",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Optimax",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Images = "[\"Medicine/cbd27a962c2c4107bf8a4adcf97f0a75.webp\"]",
                            IsDeleted = false,
                            IsPublic = true,
                            MedicineCategoryId = 1,
                            MedicineUnitId = 5,
                            Name = "Bivolet Eye Drops",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Schering",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Images = "[\"Medicine/808d7e699e5a4d4cbcdd8eeeadcbebf5.webp\"]",
                            IsDeleted = false,
                            IsPublic = false,
                            MedicineCategoryId = 2,
                            MedicineUnitId = 6,
                            Name = "Diprosone Ointment",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Brand = "B Braun",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Images = "[\"Medicine/1b6f35f7a68d4bea831ae57255ed1f6a.webp\"]",
                            IsDeleted = false,
                            IsPublic = false,
                            MedicineCategoryId = 4,
                            MedicineUnitId = 4,
                            Name = "NaCl 0.9% Infusion",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Vimed",
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Images = "[\"Medicine/08f0a64c6ca840d0a0f29d3ed5260ca7.webp\"]",
                            IsDeleted = false,
                            IsPublic = true,
                            MedicineCategoryId = 2,
                            MedicineUnitId = 7,
                            Name = "Oresol Powder",
                            Status = 1
                        });
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.MedicineCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"Name\" IS NOT NULL");

                    b.ToTable("MedicineCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Used to treat bacterial infections.",
                            Name = "Antibiotics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Used to relieve pain and reduce fever.",
                            Name = "Painkillers"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Used to support health and nutrition.",
                            Name = "Vitamins & Supplements"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Intravenous fluids and infusion solutions for hydration and therapy.",
                            Name = "Infusion Solutions"
                        });
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.MedicineSKU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<string>("SKUCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("SKUCode")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"SKUCode\" IS NOT NULL");

                    b.ToTable("MedicineSKU");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            MedicineId = 1,
                            Name = "Box 20 tablets",
                            Price = 1.5m,
                            SKUCode = "PA1BO2050"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            MedicineId = 1,
                            Name = "Box 30 tablets",
                            Price = 2m,
                            SKUCode = "PA1BO3050"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            MedicineId = 1,
                            Name = "Blister 12 tablets",
                            Price = 0.8m,
                            SKUCode = "PA1BL1250"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            MedicineId = 2,
                            Name = "Box 20 capsules",
                            Price = 2.5m,
                            SKUCode = "AM2BO2050"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            MedicineId = 2,
                            Name = "Blister 10 capsules",
                            Price = 1.2m,
                            SKUCode = "AM2BL1050"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            MedicineId = 3,
                            Name = "Box 20 tablets",
                            Price = 3m,
                            SKUCode = "VC3BO2050"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            MedicineId = 3,
                            Name = "Box 30 tablets",
                            Price = 4.5m,
                            SKUCode = "VC3BO2010"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            MedicineId = 4,
                            Name = "Bottle 30ml",
                            Price = 4m,
                            SKUCode = "AM3BO3010"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            MedicineId = 4,
                            Name = "Bottle 60ml",
                            Price = 6.5m,
                            SKUCode = "AM3BO3260"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            MedicineId = 5,
                            Name = "Bottle 10ml",
                            Price = 3.5m,
                            SKUCode = "BI5BO1050"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            MedicineId = 6,
                            Name = "Box 20 units",
                            Price = 2.8m,
                            SKUCode = "DI6BO2050"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            MedicineId = 4,
                            Name = "Bottle 250ml",
                            Price = 5m,
                            SKUCode = "NA4BO2550"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            MedicineId = 7,
                            Name = "Bottle 500ml",
                            Price = 12m,
                            SKUCode = "NA7BO5010"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            MedicineId = 8,
                            Name = "Box 20 sachets",
                            Price = 0.5m,
                            SKUCode = "OR8BO2032"
                        });
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.MedicineUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("\"Name\" IS NOT NULL");

                    b.ToTable("MedicineUnit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Solid oral dosage form pressed into flat shape",
                            Name = "Tablet"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Solid dosage form enclosed in gelatin shell",
                            Name = "Capsule"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sweet liquid oral medication",
                            Name = "Syrup"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sterile solution for parenteral administration",
                            Name = "Injection"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sterile liquid for ophthalmic use",
                            Name = "Eye Drops"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Semi-solid topical preparation",
                            Name = "Ointment"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Fine dry particles for oral or topical use",
                            Name = "Powder"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Liquid with undissolved particles",
                            Name = "Suspension"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Soluble tablet that fizzes when dissolved",
                            Name = "Effervescent"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Aerosol or pump dispenser for topical or oral use",
                            Name = "Spray"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Solid dosage form for rectal or vaginal insertion",
                            Name = "Suppository"
                        });
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.MedicineUnitOption", b =>
                {
                    b.Property<int>("MedicineUnitId")
                        .HasColumnType("int");

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("MedicineUnitId", "OptionId");

                    b.HasIndex("OptionId");

                    b.ToTable("MedicineUnitOption");

                    b.HasData(
                        new
                        {
                            MedicineUnitId = 1,
                            OptionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 1,
                            OptionId = 2,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 1,
                            OptionId = 3,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 2,
                            OptionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 2,
                            OptionId = 2,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 2,
                            OptionId = 3,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 3,
                            OptionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 3,
                            OptionId = 4,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 3,
                            OptionId = 5,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 4,
                            OptionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 4,
                            OptionId = 4,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 4,
                            OptionId = 3,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 5,
                            OptionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 5,
                            OptionId = 4,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 5,
                            OptionId = 5,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 6,
                            OptionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 6,
                            OptionId = 2,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 6,
                            OptionId = 5,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 7,
                            OptionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 7,
                            OptionId = 2,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 7,
                            OptionId = 3,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 8,
                            OptionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 8,
                            OptionId = 4,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 8,
                            OptionId = 5,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 9,
                            OptionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 9,
                            OptionId = 2,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 9,
                            OptionId = 3,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 10,
                            OptionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 10,
                            OptionId = 4,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 10,
                            OptionId = 5,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 11,
                            OptionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            MedicineUnitId = 11,
                            OptionId = 2,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OptionName")
                        .IsUnique()
                        .HasFilter("\"OptionName\" IS NOT NULL");

                    b.ToTable("Option");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OptionName = "PackagingType"
                        },
                        new
                        {
                            Id = 2,
                            OptionName = "PackQuantity"
                        },
                        new
                        {
                            Id = 3,
                            OptionName = "Dosage"
                        },
                        new
                        {
                            Id = 4,
                            OptionName = "Volume"
                        },
                        new
                        {
                            Id = 5,
                            OptionName = "Concentration"
                        });
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.OptionValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.Property<int>("UnitMultiplier")
                        .HasColumnType("int");

                    b.Property<string>("ValueName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("ValueName")
                        .IsUnique()
                        .HasFilter("\"ValueName\" IS NOT NULL");

                    b.ToTable("OptionValue");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            OptionId = 1,
                            UnitMultiplier = 1,
                            ValueName = "Box"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            OptionId = 1,
                            UnitMultiplier = 1,
                            ValueName = "Blister"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            OptionId = 1,
                            UnitMultiplier = 1,
                            ValueName = "Bottle"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            OptionId = 1,
                            UnitMultiplier = 1,
                            ValueName = "Sachet"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            OptionId = 1,
                            UnitMultiplier = 1,
                            ValueName = "Tube"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            OptionId = 1,
                            UnitMultiplier = 1,
                            ValueName = "Packet"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            OptionId = 2,
                            UnitMultiplier = 1,
                            ValueName = "1 per blister"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            OptionId = 2,
                            UnitMultiplier = 6,
                            ValueName = "6 per blister"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            OptionId = 2,
                            UnitMultiplier = 10,
                            ValueName = "10 per blister"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            OptionId = 2,
                            UnitMultiplier = 12,
                            ValueName = "12 per blister"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            OptionId = 2,
                            UnitMultiplier = 20,
                            ValueName = "20 per box"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            OptionId = 2,
                            UnitMultiplier = 30,
                            ValueName = "30 per box"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            OptionId = 2,
                            UnitMultiplier = 50,
                            ValueName = "50 per box"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            OptionId = 2,
                            UnitMultiplier = 100,
                            ValueName = "100 per box"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            OptionId = 2,
                            UnitMultiplier = 5,
                            ValueName = "5ml per bottle"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            OptionId = 2,
                            UnitMultiplier = 10,
                            ValueName = "10ml per bottle"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            OptionId = 2,
                            UnitMultiplier = 30,
                            ValueName = "30ml per bottle"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            OptionId = 2,
                            UnitMultiplier = 60,
                            ValueName = "60ml per bottle"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            OptionId = 2,
                            UnitMultiplier = 100,
                            ValueName = "100ml per bottle"
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            OptionId = 3,
                            UnitMultiplier = 1,
                            ValueName = "10mg"
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            OptionId = 3,
                            UnitMultiplier = 1,
                            ValueName = "80mg"
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            OptionId = 3,
                            UnitMultiplier = 1,
                            ValueName = "100mg"
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            OptionId = 3,
                            UnitMultiplier = 1,
                            ValueName = "250mg"
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            OptionId = 3,
                            UnitMultiplier = 1,
                            ValueName = "325mg"
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            OptionId = 3,
                            UnitMultiplier = 1,
                            ValueName = "500mg"
                        },
                        new
                        {
                            Id = 26,
                            IsActive = true,
                            OptionId = 3,
                            UnitMultiplier = 1,
                            ValueName = "650mg"
                        },
                        new
                        {
                            Id = 27,
                            IsActive = true,
                            OptionId = 3,
                            UnitMultiplier = 1,
                            ValueName = "1000mg"
                        },
                        new
                        {
                            Id = 28,
                            IsActive = true,
                            OptionId = 4,
                            UnitMultiplier = 5,
                            ValueName = "5ml"
                        },
                        new
                        {
                            Id = 29,
                            IsActive = true,
                            OptionId = 4,
                            UnitMultiplier = 10,
                            ValueName = "10ml"
                        },
                        new
                        {
                            Id = 30,
                            IsActive = true,
                            OptionId = 4,
                            UnitMultiplier = 30,
                            ValueName = "30ml"
                        },
                        new
                        {
                            Id = 31,
                            IsActive = true,
                            OptionId = 4,
                            UnitMultiplier = 60,
                            ValueName = "60ml"
                        },
                        new
                        {
                            Id = 32,
                            IsActive = true,
                            OptionId = 4,
                            UnitMultiplier = 100,
                            ValueName = "100ml"
                        },
                        new
                        {
                            Id = 33,
                            IsActive = true,
                            OptionId = 4,
                            UnitMultiplier = 250,
                            ValueName = "250ml"
                        },
                        new
                        {
                            Id = 34,
                            IsActive = true,
                            OptionId = 4,
                            UnitMultiplier = 500,
                            ValueName = "500ml"
                        },
                        new
                        {
                            Id = 35,
                            IsActive = true,
                            OptionId = 5,
                            UnitMultiplier = 1,
                            ValueName = "5mg/ml"
                        },
                        new
                        {
                            Id = 36,
                            IsActive = true,
                            OptionId = 5,
                            UnitMultiplier = 1,
                            ValueName = "10mg/ml"
                        },
                        new
                        {
                            Id = 37,
                            IsActive = true,
                            OptionId = 5,
                            UnitMultiplier = 1,
                            ValueName = "50mg/ml"
                        },
                        new
                        {
                            Id = 38,
                            IsActive = true,
                            OptionId = 5,
                            UnitMultiplier = 1,
                            ValueName = "100mg/ml"
                        },
                        new
                        {
                            Id = 39,
                            IsActive = true,
                            OptionId = 5,
                            UnitMultiplier = 1,
                            ValueName = "5%"
                        },
                        new
                        {
                            Id = 40,
                            IsActive = true,
                            OptionId = 5,
                            UnitMultiplier = 1,
                            ValueName = "10%"
                        });
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.SKUValue", b =>
                {
                    b.Property<int>("MedicineSKUId")
                        .HasColumnType("int");

                    b.Property<int>("OptionValueId")
                        .HasColumnType("int");

                    b.HasKey("MedicineSKUId", "OptionValueId");

                    b.HasIndex("OptionValueId");

                    b.ToTable("SKUValue");

                    b.HasData(
                        new
                        {
                            MedicineSKUId = 1,
                            OptionValueId = 1
                        },
                        new
                        {
                            MedicineSKUId = 1,
                            OptionValueId = 11
                        },
                        new
                        {
                            MedicineSKUId = 1,
                            OptionValueId = 25
                        },
                        new
                        {
                            MedicineSKUId = 2,
                            OptionValueId = 1
                        },
                        new
                        {
                            MedicineSKUId = 2,
                            OptionValueId = 12
                        },
                        new
                        {
                            MedicineSKUId = 2,
                            OptionValueId = 25
                        },
                        new
                        {
                            MedicineSKUId = 3,
                            OptionValueId = 2
                        },
                        new
                        {
                            MedicineSKUId = 3,
                            OptionValueId = 10
                        },
                        new
                        {
                            MedicineSKUId = 3,
                            OptionValueId = 25
                        },
                        new
                        {
                            MedicineSKUId = 4,
                            OptionValueId = 1
                        },
                        new
                        {
                            MedicineSKUId = 4,
                            OptionValueId = 11
                        },
                        new
                        {
                            MedicineSKUId = 4,
                            OptionValueId = 25
                        },
                        new
                        {
                            MedicineSKUId = 5,
                            OptionValueId = 2
                        },
                        new
                        {
                            MedicineSKUId = 5,
                            OptionValueId = 9
                        },
                        new
                        {
                            MedicineSKUId = 5,
                            OptionValueId = 25
                        },
                        new
                        {
                            MedicineSKUId = 6,
                            OptionValueId = 1
                        },
                        new
                        {
                            MedicineSKUId = 6,
                            OptionValueId = 11
                        },
                        new
                        {
                            MedicineSKUId = 6,
                            OptionValueId = 27
                        },
                        new
                        {
                            MedicineSKUId = 7,
                            OptionValueId = 1
                        },
                        new
                        {
                            MedicineSKUId = 7,
                            OptionValueId = 12
                        },
                        new
                        {
                            MedicineSKUId = 7,
                            OptionValueId = 27
                        },
                        new
                        {
                            MedicineSKUId = 8,
                            OptionValueId = 1
                        },
                        new
                        {
                            MedicineSKUId = 8,
                            OptionValueId = 17
                        },
                        new
                        {
                            MedicineSKUId = 8,
                            OptionValueId = 36
                        },
                        new
                        {
                            MedicineSKUId = 9,
                            OptionValueId = 1
                        },
                        new
                        {
                            MedicineSKUId = 9,
                            OptionValueId = 18
                        },
                        new
                        {
                            MedicineSKUId = 9,
                            OptionValueId = 39
                        },
                        new
                        {
                            MedicineSKUId = 10,
                            OptionValueId = 1
                        },
                        new
                        {
                            MedicineSKUId = 10,
                            OptionValueId = 29
                        },
                        new
                        {
                            MedicineSKUId = 10,
                            OptionValueId = 39
                        },
                        new
                        {
                            MedicineSKUId = 11,
                            OptionValueId = 1
                        },
                        new
                        {
                            MedicineSKUId = 11,
                            OptionValueId = 11
                        },
                        new
                        {
                            MedicineSKUId = 11,
                            OptionValueId = 39
                        },
                        new
                        {
                            MedicineSKUId = 12,
                            OptionValueId = 1
                        },
                        new
                        {
                            MedicineSKUId = 12,
                            OptionValueId = 33
                        },
                        new
                        {
                            MedicineSKUId = 12,
                            OptionValueId = 37
                        },
                        new
                        {
                            MedicineSKUId = 13,
                            OptionValueId = 1
                        },
                        new
                        {
                            MedicineSKUId = 13,
                            OptionValueId = 34
                        },
                        new
                        {
                            MedicineSKUId = 13,
                            OptionValueId = 38
                        },
                        new
                        {
                            MedicineSKUId = 14,
                            OptionValueId = 1
                        },
                        new
                        {
                            MedicineSKUId = 14,
                            OptionValueId = 11
                        },
                        new
                        {
                            MedicineSKUId = 14,
                            OptionValueId = 24
                        });
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.Medicine", b =>
                {
                    b.HasOne("MedicineSvc.DAL.Models.MedicineCategory", "MedicineCategory")
                        .WithMany("Medicines")
                        .HasForeignKey("MedicineCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicineSvc.DAL.Models.MedicineUnit", "MedicineUnit")
                        .WithMany("Medicines")
                        .HasForeignKey("MedicineUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicineCategory");

                    b.Navigation("MedicineUnit");
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.MedicineSKU", b =>
                {
                    b.HasOne("MedicineSvc.DAL.Models.Medicine", "Medicine")
                        .WithMany("Skus")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.MedicineUnitOption", b =>
                {
                    b.HasOne("MedicineSvc.DAL.Models.MedicineUnit", "MedicineUnit")
                        .WithMany("MedicineUnitOptions")
                        .HasForeignKey("MedicineUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicineSvc.DAL.Models.Option", "Option")
                        .WithMany("MedicineUnitOptions")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicineUnit");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.OptionValue", b =>
                {
                    b.HasOne("MedicineSvc.DAL.Models.Option", "Option")
                        .WithMany("OptionValues")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.SKUValue", b =>
                {
                    b.HasOne("MedicineSvc.DAL.Models.MedicineSKU", "MedicineSKU")
                        .WithMany("SkuValues")
                        .HasForeignKey("MedicineSKUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicineSvc.DAL.Models.OptionValue", "OptionValue")
                        .WithMany("SkuValues")
                        .HasForeignKey("OptionValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicineSKU");

                    b.Navigation("OptionValue");
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.Medicine", b =>
                {
                    b.Navigation("Skus");
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.MedicineCategory", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.MedicineSKU", b =>
                {
                    b.Navigation("SkuValues");
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.MedicineUnit", b =>
                {
                    b.Navigation("MedicineUnitOptions");

                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.Option", b =>
                {
                    b.Navigation("MedicineUnitOptions");

                    b.Navigation("OptionValues");
                });

            modelBuilder.Entity("MedicineSvc.DAL.Models.OptionValue", b =>
                {
                    b.Navigation("SkuValues");
                });
#pragma warning restore 612, 618
        }
    }
}
