export const HTML_CONTENT_SX = {
	maxWidth: '100%',
	overflowWrap: 'break-word',
	wordBreak: 'break-word',
	position: 'relative',
	'&::after': {
		content: '""',
		display: 'block',
		clear: 'both',
	},
	'& *': {
		maxWidth: '100% !important',
	},
	'& p': { mb: 1.5, lineHeight: 1.7, wordBreak: 'break-word' },
	'& h1, & h2, & h3, & h4, & h5, & h6': {
		mt: 2,
		mb: 1,
		fontWeight: 600,
		wordBreak: 'break-word',
		'&:first-child': { mt: 0 },
	},
	'& ul, & ol': { mb: 1.5, pl: 3 },
	'& li': { mb: 0.5, wordBreak: 'break-word' },
	'& img': {
		maxWidth: '100% !important',
		width: '100% !important',
		height: 'auto !important',
		borderRadius: 1,
		my: 1.5,
		display: 'block',
	},
	'& table': {
		width: '100% !important',
		display: 'block !important',
		overflowX: 'auto',
		borderCollapse: 'collapse',
		mb: 2,
	},
	'& table td, & table th': {
		border: '1px solid',
		borderColor: 'divider',
		p: 1,
		textAlign: 'left',
		wordBreak: 'break-word',
	},
	'& a': { color: 'primary.main', textDecoration: 'none', wordBreak: 'break-all' },
	'& blockquote': {
		borderLeft: 4,
		borderColor: 'primary.main',
		pl: 2,
		py: 1,
		my: 1.5,
		fontStyle: 'italic',
		wordBreak: 'break-word',
	},
	'& div': {
		maxWidth: '100% !important',
		boxSizing: 'border-box !important',
	},
	'& pre': {
		overflowX: 'auto',
		whiteSpace: 'pre-wrap',
		wordBreak: 'break-word',
	},
}

export const HTML_CONTENT_GUEST_SX = {
	maxWidth: 960,
	mx: 'auto',
	width: '100%',
	overflowWrap: 'break-word',
	wordBreak: 'break-word',
	position: 'relative',
	'&::after': {
		content: '""',
		display: 'block',
		clear: 'both',
	},
	'& *': {
		maxWidth: '100% !important',
	},
	'& p': { mb: 2, lineHeight: 1.8, wordBreak: 'break-word' },
	'& h1, & h2, & h3, & h4, & h5, & h6': {
		mt: 2,
		mb: 1.5,
		fontWeight: 600,
		wordBreak: 'break-word',
		'&:first-child': { mt: 0 },
	},
	'& h2': { mt: 3, mb: 2 },
	'& h3': { mt: 2, mb: 1.5 },
	'& ul, & ol': { mb: 2, pl: 3 },
	'& li': { mb: 0.5, wordBreak: 'break-word' },
	'& img': {
		maxWidth: '100% !important',
		width: '100% !important',
		height: 'auto !important',
		borderRadius: 1,
		my: 2,
		display: 'block',
	},
	'& table': {
		width: '100% !important',
		maxWidth: '100% !important',
		display: 'block !important',
		overflowX: 'auto',
		borderCollapse: 'collapse',
		mb: 3,
	},
	'& table td, & table th': {
		border: '1px solid',
		borderColor: 'divider',
		p: 1,
		textAlign: 'left',
		wordBreak: 'break-word',
	},
	'& iframe, & video, & embed, & object': {
		width: '100% !important',
		maxWidth: '100% !important',
		height: 'auto',
	},
	'& figure': {
		maxWidth: '100% !important',
		width: '100% !important',
		m: 0,
		'& img': {
			maxWidth: '100% !important',
			width: '100% !important',
		},
	},
	'& a': { color: 'primary.main', textDecoration: 'none', wordBreak: 'break-all' },
	'& blockquote': {
		borderLeft: 4,
		borderColor: 'primary.main',
		pl: 2,
		py: 1,
		my: 2,
		fontStyle: 'italic',
		wordBreak: 'break-word',
	},
	'& div': {
		maxWidth: '100% !important',
		width: '100% !important',
		boxSizing: 'border-box !important',
	},
	'& span': {
		wordBreak: 'break-word',
	},
	'& pre': {
		overflowX: 'auto',
		whiteSpace: 'pre-wrap',
		wordBreak: 'break-word',
	},
}
