// <auto-generated />
using System;
using MedicalHistorySvc.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalHistorySvc.DAL.Migrations
{
    [DbContext(typeof(MedicalHistoryDbContext))]
    [Migration("20260421182728_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalHistorySvc.DAL.Models.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplaintResolveStatus")
                        .HasColumnType("int");

                    b.Property<int>("ComplaintTopic")
                        .HasColumnType("int");

                    b.Property<int>("ComplaintType")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MedicalHistoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Response")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalHistoryId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = 0 AND \"MedicalHistoryId\" IS NOT NULL");

                    b.ToTable("Complaint");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComplaintResolveStatus = 2,
                            ComplaintTopic = 0,
                            ComplaintType = 2,
                            Content = "The waiting time was too long.",
                            CreationDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MedicalHistoryId = 1,
                            Response = "We are sorry for the delay. We'll improve scheduling."
                        },
                        new
                        {
                            Id = 2,
                            ComplaintResolveStatus = 3,
                            ComplaintTopic = 2,
                            ComplaintType = 1,
                            Content = "Doctor was very attentive and professional.",
                            CreationDate = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            MedicalHistoryId = 2,
                            Response = "Thank you for your feedback."
                        });
                });

            modelBuilder.Entity("MedicalHistorySvc.DAL.Models.ComplaintSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("WeekOfYear")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ComplaintSummary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Summary = "In the first week of 2026, we received 10 complaints: 6 negative, 3 neutral, and 1 positive.",
                            WeekOfYear = 1,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("MedicalHistorySvc.DAL.Models.MedicalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FollowUpAppointmentDate")
                        .HasColumnType("date");

                    b.Property<string>("MedicalHistoryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MedicalHistoryStatus")
                        .HasColumnType("int");

                    b.Property<int>("MedicalHistoryType")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PatientSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicalHistoryNumber")
                        .IsUnique()
                        .HasFilter("\"MedicalHistoryNumber\" IS NOT NULL");

                    b.ToTable("MedicalHistory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdmissionDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Common cold and mild fever.",
                            DischargeDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            FollowUpAppointmentDate = new DateOnly(2025, 1, 16),
                            MedicalHistoryNumber = "MH-OP-20250101-000000",
                            MedicalHistoryStatus = 2,
                            MedicalHistoryType = 0,
                            PatientId = 3,
                            PatientSnapshot = "{\"phone\":\"0360000003\",\"email\":\"patient@example.com\",\"name\":\"Patient User\",\"dateOfBirth\":\"1992-08-15\",\"gender\":\"Male\",\"medicalNumber\":\"PT-2025-000003\",\"height\":175,\"weight\":70,\"bloodType\":\"O\",\"allergies\":[{\"name\":\"Penicillin\",\"severityLevel\":\"Severe\",\"reaction\":\"Anaphylaxis\",\"id\":1},{\"name\":\"Dust\",\"severityLevel\":\"Mild\",\"reaction\":\"Sneezing, watery eyes\",\"id\":2}],\"id\":3}",
                            SpecialtyId = 1
                        },
                        new
                        {
                            Id = 2,
                            AdmissionDate = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Muscle pain after exercise.",
                            DischargeDate = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            FollowUpAppointmentDate = new DateOnly(2025, 1, 26),
                            MedicalHistoryNumber = "MH-OP-20250116-000000",
                            MedicalHistoryStatus = 2,
                            MedicalHistoryType = 0,
                            PatientId = 3,
                            PatientSnapshot = "{\"phone\":\"0360000003\",\"email\":\"patient@example.com\",\"name\":\"Patient User\",\"dateOfBirth\":\"1992-08-15\",\"gender\":\"Male\",\"medicalNumber\":\"PT-2025-000003\",\"height\":178,\"weight\":69,\"bloodType\":\"O\",\"allergies\":[{\"name\":\"Seafood\",\"severityLevel\":\"Moderate\",\"reaction\":\"Rash, itching\",\"id\":1}],\"id\":3}",
                            SpecialtyId = 2
                        },
                        new
                        {
                            Id = 3,
                            AdmissionDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Pneumonia requiring inpatient care.",
                            DoctorId = 4,
                            FollowUpAppointmentDate = new DateOnly(2025, 2, 10),
                            MedicalHistoryNumber = "MH-IP-20250131-000000",
                            MedicalHistoryStatus = 1,
                            MedicalHistoryType = 1,
                            PatientId = 3,
                            PatientSnapshot = "{\"phone\":\"0360000003\",\"email\":\"patient@example.com\",\"name\":\"Patient User\",\"dateOfBirth\":\"1992-08-15\",\"gender\":\"Male\",\"medicalNumber\":\"PT-2025-000003\",\"height\":178,\"weight\":69,\"bloodType\":\"O\",\"allergies\":[{\"name\":\"Penicillin\",\"severityLevel\":\"Severe\",\"reaction\":\"Anaphylaxis\",\"id\":1},{\"name\":\"Dust\",\"severityLevel\":\"Mild\",\"reaction\":\"Sneezing, watery eyes\",\"id\":2}],\"id\":3}",
                            SpecialtyId = 3
                        },
                        new
                        {
                            Id = 4,
                            AdmissionDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Post-surgery recovery for appendectomy.",
                            DoctorId = 4,
                            FollowUpAppointmentDate = new DateOnly(2025, 2, 20),
                            MedicalHistoryNumber = "MH-IP-20250205-000000",
                            MedicalHistoryStatus = 1,
                            MedicalHistoryType = 1,
                            PatientId = 3,
                            PatientSnapshot = "{\"phone\":\"0360000003\",\"email\":\"patient@example.com\",\"name\":\"Patient User\",\"dateOfBirth\":\"1992-08-15\",\"gender\":\"Male\",\"medicalNumber\":\"PT-2025-000003\",\"height\":178,\"weight\":69,\"bloodType\":\"O\",\"allergies\":[{\"name\":\"Seafood\",\"severityLevel\":\"Moderate\",\"reaction\":\"Rash, itching\",\"id\":1}],\"id\":3}",
                            SpecialtyId = 4
                        });
                });

            modelBuilder.Entity("MedicalHistorySvc.DAL.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DoctorNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MedicalHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("MedicationDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicalHistoryId")
                        .IsUnique();

                    b.ToTable("Prescription");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorNote = "Take medicine after meals.",
                            MedicalHistoryId = 1,
                            MedicationDays = 5
                        },
                        new
                        {
                            Id = 2,
                            DoctorNote = "Drink plenty of water.",
                            MedicalHistoryId = 2,
                            MedicationDays = 7
                        });
                });

            modelBuilder.Entity("MedicalHistorySvc.DAL.Models.PrescriptionDetail", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<decimal>("Dosage")
                        .HasColumnType("numeric(18, 2)");

                    b.Property<int>("FrequencyPerDay")
                        .HasColumnType("int");

                    b.Property<string>("MedicineSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrescriptionId", "MedicineId");

                    b.ToTable("PrescriptionDetail");

                    b.HasData(
                        new
                        {
                            PrescriptionId = 1,
                            MedicineId = 1,
                            Dosage = 1m,
                            FrequencyPerDay = 3,
                            MedicineSnapshot = "{\"medicineName\":\"Paracetamol\",\"medicineBrand\":\"PharmaPlus\",\"medicineImage\":\"/images/meds/paracetamol.jpg\",\"medicineUnit\":\"Tablet\"}"
                        },
                        new
                        {
                            PrescriptionId = 2,
                            MedicineId = 2,
                            Dosage = 1m,
                            FrequencyPerDay = 1,
                            MedicineSnapshot = "{\"medicineName\":\"Cetirizine\",\"medicineBrand\":\"AllerCare\",\"medicineImage\":\"/images/meds/cetirizine.jpg\",\"medicineUnit\":\"Tablet\"}"
                        });
                });

            modelBuilder.Entity("MedicalHistorySvc.DAL.Models.Complaint", b =>
                {
                    b.HasOne("MedicalHistorySvc.DAL.Models.MedicalHistory", "MedicalHistory")
                        .WithOne("Complaint")
                        .HasForeignKey("MedicalHistorySvc.DAL.Models.Complaint", "MedicalHistoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalHistory");
                });

            modelBuilder.Entity("MedicalHistorySvc.DAL.Models.Prescription", b =>
                {
                    b.HasOne("MedicalHistorySvc.DAL.Models.MedicalHistory", "MedicalHistory")
                        .WithOne("Prescription")
                        .HasForeignKey("MedicalHistorySvc.DAL.Models.Prescription", "MedicalHistoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalHistory");
                });

            modelBuilder.Entity("MedicalHistorySvc.DAL.Models.PrescriptionDetail", b =>
                {
                    b.HasOne("MedicalHistorySvc.DAL.Models.Prescription", "Prescription")
                        .WithMany("PrescriptionDetails")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MedicalHistorySvc.DAL.Models.MedicalHistory", b =>
                {
                    b.Navigation("Complaint");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MedicalHistorySvc.DAL.Models.Prescription", b =>
                {
                    b.Navigation("PrescriptionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
